# -*- coding: utf-8 -*-
from translate_helpers import bulk_translate

VIEW_ID = 1318  # home_template
SPAN = '<span style="display:block; font-size:13px; font-weight:600; color:#5a4f44; margin-bottom:6px;">{}</span>'

ROWS = [
    ("Cartotécnica Hores — Moldes de papel para panificación",
     "Cartotécnica Hores — Moldes de papel para panificación",
     "Cartotécnica Hores — Paper molds for baking",
     "Cartotécnica Hores — Moldes de papel para panificação",
     "Cartotécnica Hores — Stampi di carta per la panificazione",
     "Cartotécnica Hores — Moules en papier pour la boulangerie",
     "Cartotécnica Hores — Papierformen für die Bäckerei",
     "Cartotécnica Hores — 烘焙用纸模"),
    ("Fabricamos moldes de papel para pan dulce, budín, rosca, bizcochuelo y pan de pascua. Aptos para contacto alimentario, gestión de calidad certificada ISO 22000:2018. Bell Ville, Córdoba.",
     "Fabricamos moldes de papel para pan dulce, budín, rosca, bizcochuelo y pan de pascua. Aptos para contacto alimentario, gestión de calidad certificada ISO 22000:2018. Bell Ville, Córdoba.",
     "We manufacture paper molds for panettone, pound cake, ring cake, sponge cake and Christmas bread. Suitable for food contact, ISO 22000:2018 certified quality management. Bell Ville, Córdoba.",
     "Fabricamos moldes de papel para panetone, bolo inglês, rosca, pão de ló e pão de Natal. Próprios para contato com alimentos, gestão da qualidade certificada ISO 22000:2018. Bell Ville, Córdoba.",
     "Produciamo stampi di carta per panettone, plumcake, ciambella, pan di Spagna e pane di Pasqua. Adatti al contatto alimentare, gestione della qualità certificata ISO 22000:2018. Bell Ville, Córdoba.",
     "Nous fabriquons des moules en papier pour panettone, cake, couronne, génoise et pain de Pâques. Adaptés au contact alimentaire, gestion de la qualité certifiée ISO 22000:2018. Bell Ville, Córdoba.",
     "Wir stellen Papierformen für Panettone, Kastenform, Kranzkuchen, Biskuit und Osterbrot her. Für Lebensmittelkontakt geeignet, zertifiziertes Qualitätsmanagement ISO 22000:2018. Bell Ville, Córdoba.",
     "我们生产用于圣诞面包、磅蛋糕、环形蛋糕、海绵蛋糕和复活节面包的纸模。适合食品接触，通过ISO 22000:2018质量管理体系认证。位于科尔多瓦贝尔维尔。"),
    ("Planta Cartotécnica Hores — vista aérea",
     "Planta Cartotécnica Hores — vista aérea",
     "Cartotécnica Hores plant — aerial view",
     "Fábrica Cartotécnica Hores — vista aérea",
     "Stabilimento Cartotécnica Hores — vista aerea",
     "Usine Cartotécnica Hores — vue aérienne",
     "Werk Cartotécnica Hores — Luftaufnahme",
     "Cartotécnica Hores 工厂 — 鸟瞰图"),
    ("{{0}} — Cartotécnica Hores",) * 8,
    ('<span style="width:26px; height:2px; background:#f0b878; display:inline-block;"/> Seriedad y Eficiencia',
     '<span style="width:26px; height:2px; background:#f0b878; display:inline-block;"/> Seriedad y Eficiencia',
     '<span style="width:26px; height:2px; background:#f0b878; display:inline-block;"/> Seriousness and Efficiency',
     '<span style="width:26px; height:2px; background:#f0b878; display:inline-block;"/> Seriedade e Eficiência',
     '<span style="width:26px; height:2px; background:#f0b878; display:inline-block;"/> Serietà ed Efficienza',
     '<span style="width:26px; height:2px; background:#f0b878; display:inline-block;"/> Sérieux et Efficacité',
     '<span style="width:26px; height:2px; background:#f0b878; display:inline-block;"/> Seriosität und Effizienz',
     '<span style="width:26px; height:2px; background:#f0b878; display:inline-block;"/> 严谨与高效'),
    ("Moldes de papel para panificación", "Moldes de papel para panificación", "Paper molds for baking",
     "Moldes de papel para panificação", "Stampi di carta per la panificazione",
     "Moules en papier pour la boulangerie", "Papierformen für die Bäckerei", "烘焙用纸模"),
    ("Desarrollamos y fabricamos envases de papel para pan dulce, budín, rosca, bizcochuelo y más. Calidad para contacto alimentario, presente en toda Latinoamérica.",
     "Desarrollamos y fabricamos envases de papel para pan dulce, budín, rosca, bizcochuelo y más. Calidad para contacto alimentario, presente en toda Latinoamérica.",
     "We develop and manufacture paper packaging for panettone, pound cake, ring cake, sponge cake and more. Food-contact quality, present throughout Latin America.",
     "Desenvolvemos e fabricamos embalagens de papel para panetone, bolo inglês, rosca, pão de ló e mais. Qualidade para contato com alimentos, presentes em toda a América Latina.",
     "Sviluppiamo e produciamo confezioni di carta per panettone, plumcake, ciambella, pan di Spagna e altro ancora. Qualità per il contatto alimentare, presenti in tutta l'America Latina.",
     "Nous développons et fabriquons des emballages en papier pour panettone, cake, couronne, génoise et plus encore. Qualité pour le contact alimentaire, présents dans toute l'Amérique latine.",
     "Wir entwickeln und fertigen Papierverpackungen für Panettone, Kastenform, Kranzkuchen, Biskuit und mehr. Qualität für Lebensmittelkontakt, präsent in ganz Lateinamerika.",
     "我们开发和生产用于圣诞面包、磅蛋糕、环形蛋糕、海绵蛋糕等产品的纸质包装。适合食品接触的品质，业务遍及整个拉丁美洲。"),
    ("Ver productos", "Ver productos", "View products", "Ver produtos", "Vedi i prodotti", "Voir les produits", "Produkte ansehen", "查看产品"),
    ("Conocé la empresa", "Conocé la empresa", "Learn about us", "Conheça a empresa", "Scopri l'azienda", "Découvrir l'entreprise", "Unternehmen kennenlernen", "了解公司"),
    ("años fabricando", "años fabricando", "years in business", "anos de fabricação", "anni di attività", "ans de fabrication", "Jahre Fertigung", "年制造经验"),
    ("alcance regional", "alcance regional", "regional reach", "alcance regional", "portata regionale", "portée régionale", "regionale Reichweite", "区域覆盖"),
    ("apto alimentario", "apto alimentario", "food-safe", "apto alimentar", "idoneo alimentare", "apte au contact alimentaire", "lebensmittelecht", "食品级"),
    ("Qué hacemos", "Qué hacemos", "What we do", "O que fazemos", "Cosa facciamo", "Ce que nous faisons", "Was wir tun", "我们的业务"),
    ("Cartotécnica Hores diseña, desarrolla y fabrica moldes y envases de papel para la industria alimentaria, panaderías profesionales y grandes minoristas.",
     "Cartotécnica Hores diseña, desarrolla y fabrica moldes y envases de papel para la industria alimentaria, panaderías profesionales y grandes minoristas.",
     "Cartotécnica Hores designs, develops and manufactures paper molds and packaging for the food industry, professional bakeries and large retailers.",
     "A Cartotécnica Hores projeta, desenvolve e fabrica moldes e embalagens de papel para a indústria alimentícia, padarias profissionais e grandes varejistas.",
     "Cartotécnica Hores progetta, sviluppa e produce stampi e confezioni di carta per l'industria alimentare, panifici professionali e grande distribuzione.",
     "Cartotécnica Hores conçoit, développe et fabrique des moules et emballages en papier pour l'industrie alimentaire, les boulangeries professionnelles et la grande distribution.",
     "Cartotécnica Hores entwirft, entwickelt und fertigt Papierformen und -verpackungen für die Lebensmittelindustrie, professionelle Bäckereien und den Großhandel.",
     "Cartotécnica Hores 为食品行业、专业面包房和大型零售商设计、开发和生产纸质模具及包装。"),
    ("Investigación y Desarrollo", "Investigación y Desarrollo", "Research and Development", "Pesquisa e Desenvolvimento",
     "Ricerca e Sviluppo", "Recherche et Développement", "Forschung und Entwicklung", "研发"),
    ("Innovamos constantemente: nuevos mercados, mejores diseños y cambios positivos para el sector.",
     "Innovamos constantemente: nuevos mercados, mejores diseños y cambios positivos para el sector.",
     "We constantly innovate: new markets, better designs and positive changes for the industry.",
     "Inovamos constantemente: novos mercados, melhores designs e mudanças positivas para o setor.",
     "Innoviamo costantemente: nuovi mercati, design migliori e cambiamenti positivi per il settore.",
     "Nous innovons constamment : nouveaux marchés, meilleurs designs et changements positifs pour le secteur.",
     "Wir entwickeln uns ständig weiter: neue Märkte, bessere Designs und positive Veränderungen für die Branche.",
     "我们持续创新：开拓新市场、改进设计，为行业带来积极变化。"),
    ("Al servicio del cliente", "Al servicio del cliente", "At our clients' service", "A serviço do cliente",
     "Al servizio del cliente", "Au service du client", "Im Dienste des Kunden", "服务客户"),
    ("Fabricamos según las necesidades de cada cliente, tomándonos muy en serio la calidad.",
     "Fabricamos según las necesidades de cada cliente, tomándonos muy en serio la calidad.",
     "We manufacture according to each client's needs, taking quality very seriously.",
     "Fabricamos de acordo com as necessidades de cada cliente, levando a qualidade muito a sério.",
     "Produciamo secondo le esigenze di ogni cliente, prendendo molto sul serio la qualità.",
     "Nous fabriquons selon les besoins de chaque client, en prenant la qualité très au sérieux.",
     "Wir fertigen nach den Bedürfnissen jedes Kunden und nehmen Qualität sehr ernst.",
     "我们根据每位客户的需求进行生产，高度重视产品质量。"),
    ("Tecnología alimentaria", "Tecnología alimentaria", "Food technology", "Tecnologia alimentar",
     "Tecnologia alimentare", "Technologie alimentaire", "Lebensmitteltechnologie", "食品技术"),
    ("Línea de producción con alta tecnología que nos permite ofrecer más y mejores productos.",
     "Línea de producción con alta tecnología que nos permite ofrecer más y mejores productos.",
     "A high-tech production line that lets us offer more and better products.",
     "Linha de produção de alta tecnologia que nos permite oferecer mais e melhores produtos.",
     "Linea di produzione ad alta tecnologia che ci permette di offrire prodotti migliori e in maggior numero.",
     "Une ligne de production à haute technologie qui nous permet d'offrir plus et de meilleurs produits.",
     "Eine High-Tech-Produktionslinie, die es uns ermöglicht, mehr und bessere Produkte anzubieten.",
     "高科技生产线让我们能够提供更多、更优质的产品。"),
    ("Nuestros productos", "Nuestros productos", "Our products", "Nossos produtos", "I nostri prodotti", "Nos produits", "Unsere Produkte", "我们的产品"),
    ("Moldes para cada elaboración", "Moldes para cada elaboración", "Molds for every recipe", "Moldes para cada preparo",
     "Stampi per ogni preparazione", "Des moules pour chaque préparation", "Formen für jede Zubereitung", "适用于各类产品的模具"),
    ("Elegí una línea y accedé a su ficha técnica en un clic.",
     "Elegí una línea y accedé a su ficha técnica en un clic.",
     "Choose a line and access its spec sheet in one click.",
     "Escolha uma linha e acesse sua ficha técnica em um clique.",
     "Scegli una linea e accedi alla sua scheda tecnica con un clic.",
     "Choisissez une gamme et accédez à sa fiche technique en un clic.",
     "Wählen Sie eine Linie und rufen Sie das Datenblatt mit einem Klick auf.",
     "选择一个系列，一键查看技术规格表。"),
    ("Personalizable", "Personalizable", "Customizable", "Personalizável", "Personalizzabile", "Personnalisable", "Individualisierbar", "可定制"),
    ('<span style="font-size:13px; font-weight:600; letter-spacing:.02em; color:#c26a1e;">Ficha técnica →</span>',
     '<span style="font-size:13px; font-weight:600; letter-spacing:.02em; color:#c26a1e;">Ficha técnica →</span>',
     '<span style="font-size:13px; font-weight:600; letter-spacing:.02em; color:#c26a1e;">Spec sheet →</span>',
     '<span style="font-size:13px; font-weight:600; letter-spacing:.02em; color:#c26a1e;">Ficha técnica →</span>',
     '<span style="font-size:13px; font-weight:600; letter-spacing:.02em; color:#c26a1e;">Scheda tecnica →</span>',
     '<span style="font-size:13px; font-weight:600; letter-spacing:.02em; color:#c26a1e;">Fiche technique →</span>',
     '<span style="font-size:13px; font-weight:600; letter-spacing:.02em; color:#c26a1e;">Datenblatt →</span>',
     '<span style="font-size:13px; font-weight:600; letter-spacing:.02em; color:#c26a1e;">技术规格表 →</span>'),
    ("Calidad y certificaciones", "Calidad y certificaciones", "Quality and certifications", "Qualidade e certificações",
     "Qualità e certificazioni", "Qualité et certifications", "Qualität und Zertifizierungen", "品质与认证"),
    ("Autorizados para el contacto con alimentos", "Autorizados para el contacto con alimentos",
     "Approved for food contact", "Autorizados para contato com alimentos",
     "Autorizzati al contatto alimentare", "Autorisés au contact alimentaire",
     "Für Lebensmittelkontakt zugelassen", "获准接触食品"),
    ("Todos nuestros productos están autorizados para contacto directo con alimentos. Desarrollamos los procesos bajo un sistema de gestión de inocuidad certificado según norma ISO 22000:2018.",
     "Todos nuestros productos están autorizados para contacto directo con alimentos. Desarrollamos los procesos bajo un sistema de gestión de inocuidad certificado según norma ISO 22000:2018.",
     "All our products are approved for direct food contact. We develop our processes under a food-safety management system certified to ISO 22000:2018.",
     "Todos os nossos produtos são autorizados para contato direto com alimentos. Desenvolvemos os processos sob um sistema de gestão de inocuidade certificado conforme a norma ISO 22000:2018.",
     "Tutti i nostri prodotti sono autorizzati al contatto diretto con gli alimenti. Sviluppiamo i nostri processi nell'ambito di un sistema di gestione della sicurezza alimentare certificato secondo la norma ISO 22000:2018.",
     "Tous nos produits sont autorisés au contact direct avec les aliments. Nous développons nos processus dans le cadre d'un système de gestion de la sécurité alimentaire certifié selon la norme ISO 22000:2018.",
     "Alle unsere Produkte sind für den direkten Lebensmittelkontakt zugelassen. Wir entwickeln unsere Prozesse im Rahmen eines nach ISO 22000:2018 zertifizierten Lebensmittelsicherheitsmanagementsystems.",
     "我们所有产品均获准直接接触食品。我们按照ISO 22000:2018认证的食品安全管理体系开展生产流程。"),
    ("Ver calidad y certificaciones →", "Ver calidad y certificaciones →", "View quality and certifications →",
     "Ver qualidade e certificações →", "Vedi qualità e certificazioni →", "Voir qualité et certifications →",
     "Qualität und Zertifizierungen ansehen →", "查看品质与认证 →"),
    ("Gestión de inocuidad certificada", "Gestión de inocuidad certificada", "Certified food-safety management",
     "Gestão de inocuidade certificada", "Gestione della sicurezza alimentare certificata",
     "Gestion de la sécurité alimentaire certifiée", "Zertifiziertes Lebensmittelsicherheitsmanagement", "认证食品安全管理"),
    ("Apto", "Apto", "Approved", "Apto", "Idoneo", "Conforme", "Geeignet", "合格"),
    ("Contacto directo con alimentos", "Contacto directo con alimentos", "Direct food contact",
     "Contato direto com alimentos", "Contatto diretto con gli alimenti", "Contact direct avec les aliments",
     "Direkter Lebensmittelkontakt", "直接接触食品"),
    ("Comercialización regional", "Comercialización regional", "Regional distribution", "Comercialização regional",
     "Commercializzazione regionale", "Commercialisation régionale", "Regionaler Vertrieb", "区域销售"),
    ("Experiencia fabricando", "Experiencia fabricando", "Manufacturing experience", "Experiência fabricando",
     "Esperienza nella produzione", "Expérience de fabrication", "Fertigungserfahrung", "制造经验"),
    ("Compromiso", "Compromiso", "Commitment", "Compromisso", "Impegno", "Engagement", "Engagement", "承诺"),
    ("Compromiso con el medioambiente", "Compromiso con el medioambiente", "Commitment to the environment",
     "Compromisso com o meio ambiente", "Impegno per l'ambiente", "Engagement envers l'environnement",
     "Engagement für die Umwelt", "环境承诺"),
    ("Valorizamos el papel como materia prima renovable: trabajamos con proveedores responsables, diseñamos envases eficientes y recuperamos el scrap para minimizar el impacto ambiental.",
     "Valorizamos el papel como materia prima renovable: trabajamos con proveedores responsables, diseñamos envases eficientes y recuperamos el scrap para minimizar el impacto ambiental.",
     "We value paper as a renewable raw material: we work with responsible suppliers, design efficient packaging and recover scrap to minimize environmental impact.",
     "Valorizamos o papel como matéria-prima renovável: trabalhamos com fornecedores responsáveis, projetamos embalagens eficientes e recuperamos as aparas para minimizar o impacto ambiental.",
     "Valorizziamo la carta come materia prima rinnovabile: lavoriamo con fornitori responsabili, progettiamo confezioni efficienti e recuperiamo gli scarti per ridurre al minimo l'impatto ambientale.",
     "Nous valorisons le papier comme matière première renouvelable : nous travaillons avec des fournisseurs responsables, concevons des emballages efficaces et récupérons les chutes pour minimiser l'impact environnemental.",
     "Wir schätzen Papier als erneuerbaren Rohstoff: Wir arbeiten mit verantwortungsvollen Lieferanten zusammen, entwerfen effiziente Verpackungen und verwerten Verschnitt, um die Umweltbelastung zu minimieren.",
     "我们重视纸张作为可再生原材料的价值：与负责任的供应商合作，设计高效的包装，并回收边角料以最大限度地减少环境影响。"),
    ('<span style="width:8px; height:8px; border-radius:50%; background:#a9c48f; flex-shrink:0;"/>\n              <span style="font-size:14px; font-weight:600; color:#e7ecdf;">Bosques responsables</span>',
     '<span style="width:8px; height:8px; border-radius:50%; background:#a9c48f; flex-shrink:0;"/>\n              <span style="font-size:14px; font-weight:600; color:#e7ecdf;">Bosques responsables</span>',
     '<span style="width:8px; height:8px; border-radius:50%; background:#a9c48f; flex-shrink:0;"/>\n              <span style="font-size:14px; font-weight:600; color:#e7ecdf;">Responsible forestry</span>',
     '<span style="width:8px; height:8px; border-radius:50%; background:#a9c48f; flex-shrink:0;"/>\n              <span style="font-size:14px; font-weight:600; color:#e7ecdf;">Florestas responsáveis</span>',
     '<span style="width:8px; height:8px; border-radius:50%; background:#a9c48f; flex-shrink:0;"/>\n              <span style="font-size:14px; font-weight:600; color:#e7ecdf;">Foreste responsabili</span>',
     '<span style="width:8px; height:8px; border-radius:50%; background:#a9c48f; flex-shrink:0;"/>\n              <span style="font-size:14px; font-weight:600; color:#e7ecdf;">Forêts responsables</span>',
     '<span style="width:8px; height:8px; border-radius:50%; background:#a9c48f; flex-shrink:0;"/>\n              <span style="font-size:14px; font-weight:600; color:#e7ecdf;">Verantwortungsvolle Forstwirtschaft</span>',
     '<span style="width:8px; height:8px; border-radius:50%; background:#a9c48f; flex-shrink:0;"/>\n              <span style="font-size:14px; font-weight:600; color:#e7ecdf;">负责任的森林管理</span>'),
    ('<span style="width:8px; height:8px; border-radius:50%; background:#a9c48f; flex-shrink:0;"/>\n              <span style="font-size:14px; font-weight:600; color:#e7ecdf;">Menos desperdicio</span>',
     '<span style="width:8px; height:8px; border-radius:50%; background:#a9c48f; flex-shrink:0;"/>\n              <span style="font-size:14px; font-weight:600; color:#e7ecdf;">Menos desperdicio</span>',
     '<span style="width:8px; height:8px; border-radius:50%; background:#a9c48f; flex-shrink:0;"/>\n              <span style="font-size:14px; font-weight:600; color:#e7ecdf;">Less waste</span>',
     '<span style="width:8px; height:8px; border-radius:50%; background:#a9c48f; flex-shrink:0;"/>\n              <span style="font-size:14px; font-weight:600; color:#e7ecdf;">Menos desperdício</span>',
     '<span style="width:8px; height:8px; border-radius:50%; background:#a9c48f; flex-shrink:0;"/>\n              <span style="font-size:14px; font-weight:600; color:#e7ecdf;">Meno sprechi</span>',
     '<span style="width:8px; height:8px; border-radius:50%; background:#a9c48f; flex-shrink:0;"/>\n              <span style="font-size:14px; font-weight:600; color:#e7ecdf;">Moins de déchets</span>',
     '<span style="width:8px; height:8px; border-radius:50%; background:#a9c48f; flex-shrink:0;"/>\n              <span style="font-size:14px; font-weight:600; color:#e7ecdf;">Weniger Abfall</span>',
     '<span style="width:8px; height:8px; border-radius:50%; background:#a9c48f; flex-shrink:0;"/>\n              <span style="font-size:14px; font-weight:600; color:#e7ecdf;">减少浪费</span>'),
    ('<span style="width:8px; height:8px; border-radius:50%; background:#a9c48f; flex-shrink:0;"/>\n              <span style="font-size:14px; font-weight:600; color:#e7ecdf;">Materia prima secundaria</span>',
     '<span style="width:8px; height:8px; border-radius:50%; background:#a9c48f; flex-shrink:0;"/>\n              <span style="font-size:14px; font-weight:600; color:#e7ecdf;">Materia prima secundaria</span>',
     '<span style="width:8px; height:8px; border-radius:50%; background:#a9c48f; flex-shrink:0;"/>\n              <span style="font-size:14px; font-weight:600; color:#e7ecdf;">Secondary raw material</span>',
     '<span style="width:8px; height:8px; border-radius:50%; background:#a9c48f; flex-shrink:0;"/>\n              <span style="font-size:14px; font-weight:600; color:#e7ecdf;">Matéria-prima secundária</span>',
     '<span style="width:8px; height:8px; border-radius:50%; background:#a9c48f; flex-shrink:0;"/>\n              <span style="font-size:14px; font-weight:600; color:#e7ecdf;">Materia prima secondaria</span>',
     '<span style="width:8px; height:8px; border-radius:50%; background:#a9c48f; flex-shrink:0;"/>\n              <span style="font-size:14px; font-weight:600; color:#e7ecdf;">Matière première secondaire</span>',
     '<span style="width:8px; height:8px; border-radius:50%; background:#a9c48f; flex-shrink:0;"/>\n              <span style="font-size:14px; font-weight:600; color:#e7ecdf;">Sekundärrohstoff</span>',
     '<span style="width:8px; height:8px; border-radius:50%; background:#a9c48f; flex-shrink:0;"/>\n              <span style="font-size:14px; font-weight:600; color:#e7ecdf;">二次原料利用</span>'),
    ("Conocé nuestro compromiso →", "Conocé nuestro compromiso →", "Learn about our commitment →",
     "Conheça nosso compromisso →", "Scopri il nostro impegno →", "Découvrez notre engagement →",
     "Unser Engagement entdecken →", "了解我们的承诺 →"),
    ("Preguntas frecuentes", "Preguntas frecuentes", "Frequently asked questions", "Perguntas frequentes",
     "Domande frequenti", "Questions fréquentes", "Häufig gestellte Fragen", "常见问题"),
    ("¿Los moldes son aptos para contacto directo con alimentos?",
     "¿Los moldes son aptos para contacto directo con alimentos?",
     "Are the molds suitable for direct food contact?",
     "Os moldes são próprios para contato direto com alimentos?",
     "Gli stampi sono adatti al contatto diretto con gli alimenti?",
     "Les moules sont-ils adaptés au contact direct avec les aliments ?",
     "Sind die Formen für den direkten Lebensmittelkontakt geeignet?",
     "模具是否适合直接接触食品？"),
    ("Sí. Todos nuestros productos están autorizados para contacto con alimentos y se fabrican bajo un sistema de gestión de inocuidad certificado ISO 22000:2018.",
     "Sí. Todos nuestros productos están autorizados para contacto con alimentos y se fabrican bajo un sistema de gestión de inocuidad certificado ISO 22000:2018.",
     "Yes. All our products are approved for food contact and are manufactured under a food-safety management system certified to ISO 22000:2018.",
     "Sim. Todos os nossos produtos são autorizados para contato com alimentos e fabricados sob um sistema de gestão de inocuidade certificado ISO 22000:2018.",
     "Sì. Tutti i nostri prodotti sono autorizzati al contatto con gli alimenti e vengono fabbricati nell'ambito di un sistema di gestione della sicurezza alimentare certificato ISO 22000:2018.",
     "Oui. Tous nos produits sont autorisés au contact alimentaire et fabriqués dans le cadre d'un système de gestion de la sécurité alimentaire certifié ISO 22000:2018.",
     "Ja. Alle unsere Produkte sind für den Lebensmittelkontakt zugelassen und werden im Rahmen eines nach ISO 22000:2018 zertifizierten Lebensmittelsicherheitsmanagementsystems hergestellt.",
     "是的。我们所有产品均获准接触食品，并在通过ISO 22000:2018认证的食品安全管理体系下生产。"),
    ("¿Puedo pedir moldes personalizados o con impresión?",
     "¿Puedo pedir moldes personalizados o con impresión?",
     "Can I order custom or printed molds?",
     "Posso pedir moldes personalizados ou com impressão?",
     "Posso richiedere stampi personalizzati o stampati?",
     "Puis-je commander des moules personnalisés ou imprimés ?",
     "Kann ich individuelle oder bedruckte Formen bestellen?",
     "我可以订购定制或印刷的模具吗？"),
    ("Sí. Desarrollamos moldes a medida en distintos tamaños, gramajes e impresión personalizada según las necesidades de tu producción.",
     "Sí. Desarrollamos moldes a medida en distintos tamaños, gramajes e impresión personalizada según las necesidades de tu producción.",
     "Yes. We develop custom molds in different sizes, weights and personalized printing according to your production needs.",
     "Sim. Desenvolvemos moldes sob medida em diferentes tamanhos, gramaturas e impressão personalizada conforme as necessidades da sua produção.",
     "Sì. Sviluppiamo stampi su misura in diverse dimensioni, grammature e con stampa personalizzata secondo le esigenze della tua produzione.",
     "Oui. Nous développons des moules sur mesure dans différentes tailles, grammages et avec impression personnalisée selon les besoins de votre production.",
     "Ja. Wir entwickeln maßgeschneiderte Formen in verschiedenen Größen, Gewichten und mit individuellem Druck entsprechend den Anforderungen Ihrer Produktion.",
     "是的。我们可根据您的生产需求，提供不同尺寸、克重及个性化印刷的定制模具。"),
    ("¿Cuál es la cantidad mínima de compra?",
     "¿Cuál es la cantidad mínima de compra?",
     "What's the minimum order quantity?",
     "Qual é a quantidade mínima de compra?",
     "Qual è la quantità minima d'acquisto?",
     "Quelle est la quantité minimale de commande ?",
     "Wie hoch ist die Mindestbestellmenge?",
     "最低订购数量是多少？"),
    ("La cantidad mínima varía según el producto y si es estándar o personalizado. Escribinos y te pasamos las condiciones para tu caso.",
     "La cantidad mínima varía según el producto y si es estándar o personalizado. Escribinos y te pasamos las condiciones para tu caso.",
     "The minimum quantity varies by product and whether it's standard or custom. Write to us and we'll give you the terms for your case.",
     "A quantidade mínima varia conforme o produto e se é padrão ou personalizado. Escreva para nós e te passamos as condições para o seu caso.",
     "La quantità minima varia in base al prodotto e a seconda che sia standard o personalizzato. Scrivici e ti forniremo le condizioni per il tuo caso.",
     "La quantité minimale varie selon le produit et selon qu'il est standard ou personnalisé. Écrivez-nous et nous vous communiquerons les conditions pour votre cas.",
     "Die Mindestmenge variiert je nach Produkt und danach, ob es sich um eine Standard- oder Sonderanfertigung handelt. Schreiben Sie uns, und wir teilen Ihnen die Bedingungen für Ihren Fall mit.",
     "最低数量因产品及是否为标准品或定制品而异。请联系我们，我们将为您提供具体条件。"),
    ("¿Realizan envíos a toda Latinoamérica?",
     "¿Realizan envíos a toda Latinoamérica?",
     "Do you ship throughout Latin America?",
     "Vocês realizam envios para toda a América Latina?",
     "Effettuate spedizioni in tutta l'America Latina?",
     "Livrez-vous dans toute l'Amérique latine ?",
     "Versenden Sie in ganz Lateinamerika?",
     "你们是否配送到整个拉丁美洲？"),
    ("Sí. Nuestros productos se comercializan en toda la región. Coordinamos la logística según destino y volumen.",
     "Sí. Nuestros productos se comercializan en toda la región. Coordinamos la logística según destino y volumen.",
     "Yes. Our products are sold throughout the region. We coordinate logistics according to destination and volume.",
     "Sim. Nossos produtos são comercializados em toda a região. Coordenamos a logística conforme destino e volume.",
     "Sì. I nostri prodotti sono commercializzati in tutta la regione. Coordiniamo la logistica in base a destinazione e volume.",
     "Oui. Nos produits sont commercialisés dans toute la région. Nous coordonnons la logistique selon la destination et le volume.",
     "Ja. Unsere Produkte werden in der gesamten Region vertrieben. Wir koordinieren die Logistik je nach Zielort und Menge.",
     "是的。我们的产品销往整个地区。我们会根据目的地和数量协调物流安排。"),
    ("¿Dónde consigo la ficha técnica de un producto?",
     "¿Dónde consigo la ficha técnica de un producto?",
     "Where can I get a product's spec sheet?",
     "Onde consigo a ficha técnica de um produto?",
     "Dove trovo la scheda tecnica di un prodotto?",
     "Où puis-je trouver la fiche technique d'un produit ?",
     "Wo finde ich das Datenblatt eines Produkts?",
     "我在哪里可以获取产品的技术规格表？"),
    ("Cada producto del catálogo tiene su ficha técnica descargable en PDF, con medidas, capacidad, gramaje y material.",
     "Cada producto del catálogo tiene su ficha técnica descargable en PDF, con medidas, capacidad, gramaje y material.",
     "Every product in the catalog has a downloadable PDF spec sheet with measurements, capacity, weight and material.",
     "Cada produto do catálogo tem sua ficha técnica disponível para download em PDF, com medidas, capacidade, gramatura e material.",
     "Ogni prodotto del catalogo ha la propria scheda tecnica scaricabile in PDF, con misure, capacità, grammatura e materiale.",
     "Chaque produit du catalogue dispose d'une fiche technique téléchargeable en PDF, avec dimensions, capacité, grammage et matériau.",
     "Jedes Produkt im Katalog verfügt über ein herunterladbares PDF-Datenblatt mit Maßen, Fassungsvermögen, Gewicht und Material.",
     "目录中的每款产品都提供可下载的PDF技术规格表，包含尺寸、容量、克重和材质信息。"),
    ("Trabajá con nosotros", "Trabajá con nosotros", "Work with us", "Trabalhe conosco", "Lavora con noi",
     "Travaillez avec nous", "Arbeite mit uns", "加入我们"),
    ("Sumate al equipo de Cartotécnica Hores", "Sumate al equipo de Cartotécnica Hores",
     "Join the Cartotécnica Hores team", "Junte-se à equipe da Cartotécnica Hores",
     "Unisciti al team di Cartotécnica Hores", "Rejoignez l'équipe de Cartotécnica Hores",
     "Werde Teil des Cartotécnica-Hores-Teams", "加入 Cartotécnica Hores 团队"),
    ("Dejanos tu currículum. Lo sumamos a nuestra base de postulantes y te contactamos cuando surja una búsqueda que coincida con tu perfil.",
     "Dejanos tu currículum. Lo sumamos a nuestra base de postulantes y te contactamos cuando surja una búsqueda que coincida con tu perfil.",
     "Send us your résumé. We'll add it to our candidate pool and reach out when an opening matches your profile.",
     "Envie seu currículo. Vamos incluí-lo em nosso banco de candidatos e entrar em contato quando surgir uma vaga compatível com seu perfil.",
     "Lasciaci il tuo curriculum. Lo aggiungiamo al nostro database di candidati e ti contattiamo quando si presenta una posizione in linea con il tuo profilo.",
     "Laissez-nous votre CV. Nous l'ajoutons à notre base de candidats et vous contactons dès qu'un poste correspond à votre profil.",
     "Hinterlassen Sie uns Ihren Lebenslauf. Wir nehmen ihn in unseren Bewerberpool auf und melden uns, sobald eine passende Stelle frei wird.",
     "请提交您的简历。我们会将其纳入候选人库，一旦有合适的职位空缺即与您联系。"),
    ("Planta de Cartotécnica Hores en Bell Ville", "Planta de Cartotécnica Hores en Bell Ville",
     "Cartotécnica Hores plant in Bell Ville", "Fábrica da Cartotécnica Hores em Bell Ville",
     "Stabilimento Cartotécnica Hores a Bell Ville", "Usine Cartotécnica Hores à Bell Ville",
     "Werk Cartotécnica Hores in Bell Ville", "位于贝尔维尔的 Cartotécnica Hores 工厂"),
    ("Revisá el formulario: completá nombre y un email válido.",
     "Revisá el formulario: completá nombre y un email válido.",
     "Check the form: fill in your name and a valid email.",
     "Confira o formulário: preencha o nome e um email válido.",
     "Controlla il modulo: inserisci nome e un'email valida.",
     "Vérifiez le formulaire : indiquez un nom et un email valide.",
     "Bitte überprüfen Sie das Formular: Name und gültige E-Mail-Adresse eingeben.",
     "请检查表单：填写姓名和有效的电子邮箱。"),
    ("Falta adjuntar tu currículum.", "Falta adjuntar tu currículum.", "You need to attach your résumé.",
     "Falta anexar seu currículo.", "Devi allegare il tuo curriculum.", "Vous devez joindre votre CV.",
     "Bitte fügen Sie Ihren Lebenslauf bei.", "请上传您的简历。"),
    ("El currículum tiene que ser un PDF o un Word (.pdf, .doc, .docx).",
     "El currículum tiene que ser un PDF o un Word (.pdf, .doc, .docx).",
     "Your résumé needs to be a PDF or Word file (.pdf, .doc, .docx).",
     "O currículo precisa ser um PDF ou Word (.pdf, .doc, .docx).",
     "Il curriculum deve essere un PDF o un Word (.pdf, .doc, .docx).",
     "Le CV doit être un fichier PDF ou Word (.pdf, .doc, .docx).",
     "Der Lebenslauf muss eine PDF- oder Word-Datei sein (.pdf, .doc, .docx).",
     "简历文件必须是PDF或Word格式（.pdf、.doc、.docx）。"),
    ("El archivo pesa demasiado — el límite es 5 MB.",
     "El archivo pesa demasiado — el límite es 5 MB.",
     "The file is too large — the limit is 5 MB.",
     "O arquivo é muito grande — o limite é 5 MB.",
     "Il file è troppo pesante — il limite è 5 MB.",
     "Le fichier est trop volumineux — la limite est de 5 Mo.",
     "Die Datei ist zu groß — das Limit liegt bei 5 MB.",
     "文件过大 — 上限为5MB。"),
    (SPAN.format("Nombre*"), SPAN.format("Nombre*"), SPAN.format("Name*"), SPAN.format("Nome*"),
     SPAN.format("Nome*"), SPAN.format("Nom*"), SPAN.format("Name*"), SPAN.format("姓名*")),
    (SPAN.format("Teléfono"), SPAN.format("Teléfono"), SPAN.format("Phone"), SPAN.format("Telefone"),
     SPAN.format("Telefono"), SPAN.format("Téléphone"), SPAN.format("Telefon"), SPAN.format("电话")),
    (SPAN.format("Email*"), SPAN.format("Email*"), SPAN.format("Email*"), SPAN.format("Email*"),
     SPAN.format("Email*"), SPAN.format("E-mail*"), SPAN.format("E-Mail*"), SPAN.format("邮箱*")),
    (SPAN.format("Área de interés"), SPAN.format("Área de interés"), SPAN.format("Area of interest"),
     SPAN.format("Área de interesse"), SPAN.format("Area di interesse"), SPAN.format("Domaine d'intérêt"),
     SPAN.format("Interessenbereich"), SPAN.format("意向岗位")),
    ("Ej: Producción, Administración, Mantenimiento...", "Ej: Producción, Administración, Mantenimiento...",
     "E.g.: Production, Administration, Maintenance...", "Ex.: Produção, Administração, Manutenção...",
     "Es.: Produzione, Amministrazione, Manutenzione...", "Ex. : Production, Administration, Maintenance...",
     "Z. B.: Produktion, Verwaltung, Wartung...", "例如：生产、行政、维护……"),
    (SPAN.format("Comentario"), SPAN.format("Comentario"), SPAN.format("Comment"), SPAN.format("Comentário"),
     SPAN.format("Commento"), SPAN.format("Commentaire"), SPAN.format("Kommentar"), SPAN.format("留言")),
    (SPAN.format("Currículum*"), SPAN.format("Currículum*"), SPAN.format("Résumé*"), SPAN.format("Currículo*"),
     SPAN.format("Curriculum*"), SPAN.format("CV*"), SPAN.format("Lebenslauf*"), SPAN.format("简历*")),
    ('<span style="display:block; font-size:12px; color:#8a7a67; margin-top:6px;">PDF o Word, hasta 5 MB.</span>',
     '<span style="display:block; font-size:12px; color:#8a7a67; margin-top:6px;">PDF o Word, hasta 5 MB.</span>',
     '<span style="display:block; font-size:12px; color:#8a7a67; margin-top:6px;">PDF or Word, up to 5 MB.</span>',
     '<span style="display:block; font-size:12px; color:#8a7a67; margin-top:6px;">PDF ou Word, até 5 MB.</span>',
     '<span style="display:block; font-size:12px; color:#8a7a67; margin-top:6px;">PDF o Word, fino a 5 MB.</span>',
     '<span style="display:block; font-size:12px; color:#8a7a67; margin-top:6px;">PDF ou Word, jusqu\'à 5 Mo.</span>',
     '<span style="display:block; font-size:12px; color:#8a7a67; margin-top:6px;">PDF oder Word, bis zu 5 MB.</span>',
     '<span style="display:block; font-size:12px; color:#8a7a67; margin-top:6px;">PDF或Word格式，最大5MB。</span>'),
    ("Enviar postulación", "Enviar postulación", "Submit application", "Enviar candidatura", "Invia candidatura",
     "Envoyer la candidature", "Bewerbung senden", "提交申请"),
    ("¿Necesitás una solución a medida?", "¿Necesitás una solución a medida?", "Need a custom solution?",
     "Precisa de uma solução sob medida?", "Hai bisogno di una soluzione su misura?",
     "Besoin d'une solution sur mesure ?", "Brauchen Sie eine maßgeschneiderte Lösung?", "需要定制解决方案吗？"),
    ("Contactanos y desarrollamos el molde que tu producción necesita.",
     "Contactanos y desarrollamos el molde que tu producción necesita.",
     "Contact us and we'll develop the mold your production needs.",
     "Entre em contato e desenvolvemos o molde que sua produção precisa.",
     "Contattaci e sviluppiamo lo stampo di cui la tua produzione ha bisogno.",
     "Contactez-nous et nous développerons le moule dont votre production a besoin.",
     "Kontaktieren Sie uns, und wir entwickeln die Form, die Ihre Produktion braucht.",
     "联系我们，为您的生产需求量身定制模具。"),
    ("Línea directa 3537 427085", "Línea directa 3537 427085", "Direct line 3537 427085",
     "Linha direta 3537 427085", "Linea diretta 3537 427085", "Ligne directe 3537 427085",
     "Direktleitung 3537 427085", "直线电话 3537 427085"),
    ("Escribinos", "Escribinos", "Write to us", "Escreva-nos", "Scrivici", "Écrivez-nous", "Schreiben Sie uns", "联系我们"),
    ("Completá el formulario y te respondemos a la brevedad. También podés escribirnos por WhatsApp, email o acercarte a la planta.",
     "Completá el formulario y te respondemos a la brevedad. También podés escribirnos por WhatsApp, email o acercarte a la planta.",
     "Fill out the form and we'll get back to you shortly. You can also write to us on WhatsApp, by email, or visit the plant.",
     "Preencha o formulário e responderemos em breve. Você também pode nos escrever pelo WhatsApp, e-mail ou visitar a fábrica.",
     "Compila il modulo e ti risponderemo a breve. Puoi anche scriverci su WhatsApp, via email o venire in stabilimento.",
     "Remplissez le formulaire et nous vous répondrons rapidement. Vous pouvez aussi nous écrire sur WhatsApp, par email ou venir à l'usine.",
     "Füllen Sie das Formular aus, wir melden uns umgehend. Sie können uns auch per WhatsApp, E-Mail oder persönlich im Werk erreichen.",
     "填写表单，我们会尽快回复您。您也可以通过WhatsApp、电子邮件联系我们，或亲临工厂。"),
    ('<span><strong style="display:block; color:#241d17;">Email</strong>administracion@hores.com.ar</span>',
     '<span><strong style="display:block; color:#241d17;">Email</strong>administracion@hores.com.ar</span>',
     '<span><strong style="display:block; color:#241d17;">Email</strong>administracion@hores.com.ar</span>',
     '<span><strong style="display:block; color:#241d17;">E-mail</strong>administracion@hores.com.ar</span>',
     '<span><strong style="display:block; color:#241d17;">Email</strong>administracion@hores.com.ar</span>',
     '<span><strong style="display:block; color:#241d17;">E-mail</strong>administracion@hores.com.ar</span>',
     '<span><strong style="display:block; color:#241d17;">E-Mail</strong>administracion@hores.com.ar</span>',
     '<span><strong style="display:block; color:#241d17;">邮箱</strong>administracion@hores.com.ar</span>'),
    ('<span style="width:38px; height:38px; border-radius:9px; background:#efe6d8; display:flex; align-items:center; justify-content:center; color:#8a7a67; font-weight:700;">◎</span>\n            <span><strong style="display:block; color:#241d17;">Planta</strong>Ruta Prov. 3, Km. 183.5, Bell Ville, Córdoba</span>',
     '<span style="width:38px; height:38px; border-radius:9px; background:#efe6d8; display:flex; align-items:center; justify-content:center; color:#8a7a67; font-weight:700;">◎</span>\n            <span><strong style="display:block; color:#241d17;">Planta</strong>Ruta Prov. 3, Km. 183.5, Bell Ville, Córdoba</span>',
     '<span style="width:38px; height:38px; border-radius:9px; background:#efe6d8; display:flex; align-items:center; justify-content:center; color:#8a7a67; font-weight:700;">◎</span>\n            <span><strong style="display:block; color:#241d17;">Plant</strong>Ruta Prov. 3, Km. 183.5, Bell Ville, Córdoba</span>',
     '<span style="width:38px; height:38px; border-radius:9px; background:#efe6d8; display:flex; align-items:center; justify-content:center; color:#8a7a67; font-weight:700;">◎</span>\n            <span><strong style="display:block; color:#241d17;">Fábrica</strong>Ruta Prov. 3, Km. 183.5, Bell Ville, Córdoba</span>',
     '<span style="width:38px; height:38px; border-radius:9px; background:#efe6d8; display:flex; align-items:center; justify-content:center; color:#8a7a67; font-weight:700;">◎</span>\n            <span><strong style="display:block; color:#241d17;">Stabilimento</strong>Ruta Prov. 3, Km. 183.5, Bell Ville, Córdoba</span>',
     '<span style="width:38px; height:38px; border-radius:9px; background:#efe6d8; display:flex; align-items:center; justify-content:center; color:#8a7a67; font-weight:700;">◎</span>\n            <span><strong style="display:block; color:#241d17;">Usine</strong>Ruta Prov. 3, Km. 183.5, Bell Ville, Córdoba</span>',
     '<span style="width:38px; height:38px; border-radius:9px; background:#efe6d8; display:flex; align-items:center; justify-content:center; color:#8a7a67; font-weight:700;">◎</span>\n            <span><strong style="display:block; color:#241d17;">Werk</strong>Ruta Prov. 3, Km. 183.5, Bell Ville, Córdoba</span>',
     '<span style="width:38px; height:38px; border-radius:9px; background:#efe6d8; display:flex; align-items:center; justify-content:center; color:#8a7a67; font-weight:700;">◎</span>\n            <span><strong style="display:block; color:#241d17;">工厂</strong>Ruta Prov. 3, Km. 183.5, Bell Ville, Córdoba</span>'),
    ("Ubicación Cartotécnica Hores — Bell Ville", "Ubicación Cartotécnica Hores — Bell Ville",
     "Cartotécnica Hores location — Bell Ville", "Localização Cartotécnica Hores — Bell Ville",
     "Posizione Cartotécnica Hores — Bell Ville", "Localisation Cartotécnica Hores — Bell Ville",
     "Standort Cartotécnica Hores — Bell Ville", "Cartotécnica Hores 位置 — 贝尔维尔"),
    ("Cómo llegar →", "Cómo llegar →", "Get directions →", "Como chegar →", "Come arrivare →",
     "Itinéraire →", "Anfahrt →", "路线指引 →"),
    ("Revisá el formulario: completá nombre, email y mensaje, con un email válido.",
     "Revisá el formulario: completá nombre, email y mensaje, con un email válido.",
     "Check the form: fill in name, email and message, with a valid email.",
     "Revise o formulário: preencha nome, email e mensagem, com um email válido.",
     "Controlla il modulo: inserisci nome, email e messaggio, con un'email valida.",
     "Vérifiez le formulaire : indiquez nom, email et message, avec un email valide.",
     "Bitte überprüfen Sie das Formular: Name, E-Mail und Nachricht ausfüllen, mit gültiger E-Mail-Adresse.",
     "请检查表单：填写姓名、邮箱和留言内容，并确保邮箱地址有效。"),
    (SPAN.format("Empresa"), SPAN.format("Empresa"), SPAN.format("Company"), SPAN.format("Empresa"),
     SPAN.format("Azienda"), SPAN.format("Entreprise"), SPAN.format("Unternehmen"), SPAN.format("公司")),
    (SPAN.format("Mensaje*"), SPAN.format("Mensaje*"), SPAN.format("Message*"), SPAN.format("Mensagem*"),
     SPAN.format("Messaggio*"), SPAN.format("Message*"), SPAN.format("Nachricht*"), SPAN.format("留言*")),
    ("Enviar consulta", "Enviar consulta", "Send inquiry", "Enviar consulta", "Invia richiesta",
     "Envoyer la demande", "Anfrage senden", "发送咨询"),
]

bulk_translate(VIEW_ID, ROWS)
