# -*- coding: utf-8 -*-
from translate_helpers import bulk_translate

VIEW_ID = 1446  # compromiso_template

ROWS = [
    ("Compromiso ambiental — Cartotécnica Hores", "Compromiso ambiental — Cartotécnica Hores",
     "Environmental commitment — Cartotécnica Hores", "Compromisso ambiental — Cartotécnica Hores",
     "Impegno ambientale — Cartotécnica Hores", "Engagement environnemental — Cartotécnica Hores",
     "Umweltengagement — Cartotécnica Hores", "环境承诺 — Cartotécnica Hores"),
    ("Trabajamos con proveedores responsables, diseñamos envases eficientes y recuperamos el scrap de papel para minimizar el impacto ambiental de nuestra producción.",
     "Trabajamos con proveedores responsables, diseñamos envases eficientes y recuperamos el scrap de papel para minimizar el impacto ambiental de nuestra producción.",
     "We work with responsible suppliers, design efficient packaging and recover paper scrap to minimize the environmental impact of our production.",
     "Trabalhamos com fornecedores responsáveis, projetamos embalagens eficientes e recuperamos as aparas de papel para minimizar o impacto ambiental de nossa produção.",
     "Lavoriamo con fornitori responsabili, progettiamo confezioni efficienti e recuperiamo gli scarti di carta per ridurre al minimo l'impatto ambientale della nostra produzione.",
     "Nous travaillons avec des fournisseurs responsables, concevons des emballages efficaces et récupérons les chutes de papier pour minimiser l'impact environnemental de notre production.",
     "Wir arbeiten mit verantwortungsvollen Lieferanten zusammen, entwerfen effiziente Verpackungen und verwerten Papierverschnitt, um die Umweltbelastung unserer Produktion zu minimieren.",
     "我们与负责任的供应商合作，设计高效包装，并回收纸张边角料，以最大限度地减少生产对环境的影响。"),
    ("Naturaleza — compromiso ambiental Cartotécnica Hores", "Naturaleza — compromiso ambiental Cartotécnica Hores",
     "Nature — Cartotécnica Hores environmental commitment", "Natureza — compromisso ambiental Cartotécnica Hores",
     "Natura — impegno ambientale Cartotécnica Hores", "Nature — engagement environnemental Cartotécnica Hores",
     "Natur — Umweltengagement von Cartotécnica Hores", "自然 — Cartotécnica Hores 环境承诺"),
    ("Inicio", "Inicio", "Home", "Início", "Home", "Accueil", "Startseite", "首页"),
    ('<span style="opacity:.6;">/</span> Compromiso', '<span style="opacity:.6;">/</span> Compromiso',
     '<span style="opacity:.6;">/</span> Commitment', '<span style="opacity:.6;">/</span> Compromisso',
     '<span style="opacity:.6;">/</span> Impegno', '<span style="opacity:.6;">/</span> Engagement',
     '<span style="opacity:.6;">/</span> Engagement', '<span style="opacity:.6;">/</span> 承诺'),
    ('<span style="width:26px; height:2px; background:#a9c48f; display:inline-block;"/> Compromiso',
     '<span style="width:26px; height:2px; background:#a9c48f; display:inline-block;"/> Compromiso',
     '<span style="width:26px; height:2px; background:#a9c48f; display:inline-block;"/> Commitment',
     '<span style="width:26px; height:2px; background:#a9c48f; display:inline-block;"/> Compromisso',
     '<span style="width:26px; height:2px; background:#a9c48f; display:inline-block;"/> Impegno',
     '<span style="width:26px; height:2px; background:#a9c48f; display:inline-block;"/> Engagement',
     '<span style="width:26px; height:2px; background:#a9c48f; display:inline-block;"/> Engagement',
     '<span style="width:26px; height:2px; background:#a9c48f; display:inline-block;"/> 承诺'),
    ("Compromiso con el medioambiente y respeto por la naturaleza", "Compromiso con el medioambiente y respeto por la naturaleza",
     "Commitment to the environment and respect for nature", "Compromisso com o meio ambiente e respeito pela natureza",
     "Impegno per l'ambiente e rispetto per la natura", "Engagement envers l'environnement et respect de la nature",
     "Engagement für die Umwelt und Respekt vor der Natur", "环境承诺与自然尊重"),
    ("El papel es una materia prima renovable y reciclable. Trabajamos para aprovecharlo de manera responsable en cada etapa, reduciendo el impacto ambiental de nuestra actividad.",
     "El papel es una materia prima renovable y reciclable. Trabajamos para aprovecharlo de manera responsable en cada etapa, reduciendo el impacto ambiental de nuestra actividad.",
     "Paper is a renewable and recyclable raw material. We work to use it responsibly at every stage, reducing the environmental impact of our activity.",
     "O papel é uma matéria-prima renovável e reciclável. Trabalhamos para aproveitá-lo de forma responsável em cada etapa, reduzindo o impacto ambiental de nossa atividade.",
     "La carta è una materia prima rinnovabile e riciclabile. Lavoriamo per utilizzarla in modo responsabile in ogni fase, riducendo l'impatto ambientale della nostra attività.",
     "Le papier est une matière première renouvelable et recyclable. Nous nous efforçons de l'utiliser de manière responsable à chaque étape, en réduisant l'impact environnemental de notre activité.",
     "Papier ist ein erneuerbarer und recycelbarer Rohstoff. Wir setzen ihn in jeder Phase verantwortungsvoll ein und reduzieren so die Umweltbelastung unserer Tätigkeit.",
     "纸张是一种可再生、可回收的原材料。我们努力在生产的每个环节负责任地利用它，减少我们业务活动对环境的影响。"),
    ("Producimos pensando en las próximas generaciones", "Producimos pensando en las próximas generaciones",
     "We produce with future generations in mind", "Produzimos pensando nas próximas gerações",
     "Produciamo pensando alle prossime generazioni", "Nous produisons en pensant aux générations futures",
     "Wir produzieren im Hinblick auf künftige Generationen", "我们的生产着眼于子孙后代"),
    ("La industria del papel se basa en un recurso natural, renovable y biodegradable. Asumimos la responsabilidad de gestionarlo con criterio: elegimos proveedores comprometidos con el manejo responsable de los bosques, optimizamos nuestros procesos para generar menos desperdicio y recuperamos el papel como recurso.",
     "La industria del papel se basa en un recurso natural, renovable y biodegradable. Asumimos la responsabilidad de gestionarlo con criterio: elegimos proveedores comprometidos con el manejo responsable de los bosques, optimizamos nuestros procesos para generar menos desperdicio y recuperamos el papel como recurso.",
     "The paper industry is based on a natural, renewable and biodegradable resource. We take responsibility for managing it wisely: we choose suppliers committed to responsible forest management, optimize our processes to generate less waste and recover paper as a resource.",
     "A indústria do papel se baseia em um recurso natural, renovável e biodegradável. Assumimos a responsabilidade de gerenciá-lo com critério: escolhemos fornecedores comprometidos com o manejo responsável das florestas, otimizamos nossos processos para gerar menos desperdício e recuperamos o papel como recurso.",
     "L'industria della carta si basa su una risorsa naturale, rinnovabile e biodegradabile. Ci assumiamo la responsabilità di gestirla con criterio: scegliamo fornitori impegnati nella gestione responsabile delle foreste, ottimizziamo i nostri processi per generare meno rifiuti e recuperiamo la carta come risorsa.",
     "L'industrie du papier repose sur une ressource naturelle, renouvelable et biodégradable. Nous assumons la responsabilité de la gérer judicieusement : nous choisissons des fournisseurs engagés dans une gestion responsable des forêts, optimisons nos processus pour générer moins de déchets et récupérons le papier comme ressource.",
     "Die Papierindustrie basiert auf einer natürlichen, erneuerbaren und biologisch abbaubaren Ressource. Wir übernehmen die Verantwortung, sie umsichtig zu verwalten: Wir wählen Lieferanten, die sich für eine verantwortungsvolle Waldbewirtschaftung einsetzen, optimieren unsere Prozesse, um weniger Abfall zu erzeugen, und verwerten Papier als Ressource.",
     "造纸行业依赖于一种天然、可再生、可生物降解的资源。我们负责任地对其进行管理：选择致力于负责任森林管理的供应商，优化流程以减少废弃物，并将纸张作为资源加以回收利用。"),
    ("Bosques responsables", "Bosques responsables", "Responsible forestry", "Florestas responsáveis",
     "Foreste responsabili", "Forêts responsables", "Verantwortungsvolle Forstwirtschaft", "负责任的森林管理"),
    ("Proveedores comprometidos con una adecuada administración de los bosques y la reposición de la materia prima.",
     "Proveedores comprometidos con una adecuada administración de los bosques y la reposición de la materia prima.",
     "Suppliers committed to proper forest management and raw-material replenishment.",
     "Fornecedores comprometidos com a administração adequada das florestas e a reposição da matéria-prima.",
     "Fornitori impegnati in una corretta gestione delle foreste e nel ripristino della materia prima.",
     "Fournisseurs engagés dans une gestion adéquate des forêts et le renouvellement des matières premières.",
     "Lieferanten, die sich für eine angemessene Waldbewirtschaftung und die Erneuerung der Rohstoffe einsetzen.",
     "致力于合理森林管理及原材料补给的供应商。"),
    ("Menos desperdicio", "Menos desperdicio", "Less waste", "Menos desperdício", "Meno sprechi",
     "Moins de déchets", "Weniger Abfall", "减少浪费"),
    ("Ingeniería de procesos y diseño de envases eficientes para minimizar el scrap de material.",
     "Ingeniería de procesos y diseño de envases eficientes para minimizar el scrap de material.",
     "Process engineering and efficient packaging design to minimize material scrap.",
     "Engenharia de processos e design de embalagens eficientes para minimizar as aparas de material.",
     "Ingegneria dei processi e design di confezioni efficienti per ridurre al minimo gli scarti di materiale.",
     "Ingénierie des processus et conception d'emballages efficaces pour minimiser les chutes de matériau.",
     "Prozesstechnik und effizientes Verpackungsdesign zur Minimierung von Materialverschnitt.",
     "通过工艺工程与高效包装设计，最大限度减少材料废弃。"),
    ("Materia prima secundaria", "Materia prima secundaria", "Secondary raw material", "Matéria-prima secundária",
     "Materia prima secondaria", "Matière première secondaire", "Sekundärrohstoff", "二次原料利用"),
    ("Recuperamos el scrap de papel y lo revalorizamos como recurso, cerrando el ciclo.",
     "Recuperamos el scrap de papel y lo revalorizamos como recurso, cerrando el ciclo.",
     "We recover paper scrap and repurpose it as a resource, closing the loop.",
     "Recuperamos as aparas de papel e as revalorizamos como recurso, fechando o ciclo.",
     "Recuperiamo gli scarti di carta e li rivalorizziamo come risorsa, chiudendo il ciclo.",
     "Nous récupérons les chutes de papier et les revalorisons comme ressource, bouclant ainsi le cycle.",
     "Wir verwerten Papierverschnitt und werten ihn als Ressource auf und schließen so den Kreislauf.",
     "我们回收纸张边角料并将其转化为资源，实现循环利用。"),
    ("Un recurso renovable, bien administrado", "Un recurso renovable, bien administrado",
     "A renewable resource, well managed", "Um recurso renovável, bem administrado",
     "Una risorsa rinnovabile, ben gestita", "Une ressource renouvelable, bien gérée",
     "Eine erneuerbare Ressource, gut verwaltet", "管理良好的可再生资源"),
    ('Trabajamos con proveedores comprometidos con la sustentabilidad y el manejo adecuado de los bosques, bajo esquemas certificados <strong style="color:#1c2124;">FSC</strong>, y contamos además con autorizaciones <strong style="color:#1c2124;">ISEGA</strong> para el contacto directo de nuestros moldes con alimentos.',
     'Trabajamos con proveedores comprometidos con la sustentabilidad y el manejo adecuado de los bosques, bajo esquemas certificados <strong style="color:#1c2124;">FSC</strong>, y contamos además con autorizaciones <strong style="color:#1c2124;">ISEGA</strong> para el contacto directo de nuestros moldes con alimentos.',
     'We work with suppliers committed to sustainability and proper forest management, under certified <strong style="color:#1c2124;">FSC</strong> schemes, and we also hold <strong style="color:#1c2124;">ISEGA</strong> authorizations for the direct contact of our molds with food.',
     'Trabalhamos com fornecedores comprometidos com a sustentabilidade e o manejo adequado das florestas, sob esquemas certificados <strong style="color:#1c2124;">FSC</strong>, e contamos também com autorizações <strong style="color:#1c2124;">ISEGA</strong> para o contato direto de nossos moldes com alimentos.',
     'Lavoriamo con fornitori impegnati nella sostenibilità e nella corretta gestione delle foreste, secondo schemi certificati <strong style="color:#1c2124;">FSC</strong>, e disponiamo inoltre di autorizzazioni <strong style="color:#1c2124;">ISEGA</strong> per il contatto diretto dei nostri stampi con gli alimenti.',
     'Nous travaillons avec des fournisseurs engagés dans la durabilité et la bonne gestion des forêts, selon des schémas certifiés <strong style="color:#1c2124;">FSC</strong>, et nous disposons également d\'autorisations <strong style="color:#1c2124;">ISEGA</strong> pour le contact direct de nos moules avec les aliments.',
     'Wir arbeiten mit Lieferanten zusammen, die sich für Nachhaltigkeit und eine angemessene Waldbewirtschaftung einsetzen, nach zertifizierten <strong style="color:#1c2124;">FSC</strong>-Standards, und verfügen zudem über <strong style="color:#1c2124;">ISEGA</strong>-Zulassungen für den direkten Kontakt unserer Formen mit Lebensmitteln.',
     '我们与致力于可持续发展和合理森林管理的供应商合作，符合<strong style="color:#1c2124;">FSC</strong>认证体系，并持有<strong style="color:#1c2124;">ISEGA</strong>认证，允许我们的模具直接接触食品。'),
    ("El papel es, además, uno de los materiales más reciclados y biodegradables, lo que reduce su huella respecto de otras alternativas de envase.",
     "El papel es, además, uno de los materiales más reciclados y biodegradables, lo que reduce su huella respecto de otras alternativas de envase.",
     "Paper is also one of the most recycled and biodegradable materials, which reduces its footprint compared to other packaging alternatives.",
     "O papel é, além disso, um dos materiais mais reciclados e biodegradáveis, o que reduz sua pegada em relação a outras alternativas de embalagem.",
     "La carta è inoltre uno dei materiali più riciclati e biodegradabili, il che ne riduce l'impronta rispetto ad altre alternative di imballaggio.",
     "Le papier est également l'un des matériaux les plus recyclés et biodégradables, ce qui réduit son empreinte par rapport à d'autres alternatives d'emballage.",
     "Papier ist zudem eines der am meisten recycelten und biologisch abbaubaren Materialien, was seinen Fußabdruck im Vergleich zu anderen Verpackungsalternativen verringert.",
     "此外，纸张也是回收率和可生物降解性最高的材料之一，相比其他包装材料，其环境足迹更小。"),
    ("Bosque — administración responsable", "Bosque — administración responsable", "Forest — responsible management",
     "Floresta — administração responsável", "Foresta — gestione responsabile", "Forêt — gestion responsable",
     "Wald — verantwortungsvolle Bewirtschaftung", "森林 — 负责任的管理"),
    ("Residuos y agua", "Residuos y agua", "Waste and water", "Resíduos e água", "Rifiuti e acqua",
     "Déchets et eau", "Abfall und Wasser", "废弃物与水资源"),
    ("Cómo cuidamos lo que sale de planta", "Cómo cuidamos lo que sale de planta", "How we manage what leaves the plant",
     "Como cuidamos do que sai da fábrica", "Come gestiamo ciò che esce dallo stabilimento",
     "Comment nous gérons ce qui sort de l'usine", "Wie wir mit dem umgehen, was unser Werk verlässt",
     "我们如何管理厂区排放物"),
    ("Separación de residuos", "Separación de residuos", "Waste separation", "Separação de resíduos",
     "Separazione dei rifiuti", "Tri des déchets", "Abfalltrennung", "废弃物分类"),
    ("Procedimientos internos de control y separación, coordinando con recicladoras externas la disposición final de papeles, plásticos, lubricantes y demás scrap del proceso.",
     "Procedimientos internos de control y separación, coordinando con recicladoras externas la disposición final de papeles, plásticos, lubricantes y demás scrap del proceso.",
     "Internal control and separation procedures, coordinating with external recyclers on the final disposal of paper, plastics, lubricants and other process scrap.",
     "Procedimentos internos de controle e separação, coordenando com recicladoras externas a destinação final de papéis, plásticos, lubrificantes e demais resíduos do processo.",
     "Procedure interne di controllo e separazione, coordinandoci con impianti di riciclaggio esterni per lo smaltimento finale di carta, plastica, lubrificanti e altri scarti di processo.",
     "Procédures internes de contrôle et de tri, en coordination avec des recycleurs externes pour l'élimination finale du papier, des plastiques, des lubrifiants et autres déchets du processus.",
     "Interne Kontroll- und Trennverfahren, in Abstimmung mit externen Recyclingunternehmen für die endgültige Entsorgung von Papier, Kunststoffen, Schmierstoffen und anderen Prozessabfällen.",
     "建立内部管控与分类流程，并与外部回收企业协作，妥善处理生产过程中产生的纸张、塑料、润滑油等废弃物。"),
    ("Tratamiento de agua", "Tratamiento de agua", "Water treatment", "Tratamento de água", "Trattamento delle acque",
     "Traitement de l'eau", "Wasseraufbereitung", "水处理"),
    ("Tratamos las aguas residuales del lavado de nuestras impresoras flexográficas, para reducir el agua utilizada y minimizar el impacto ambiental.",
     "Tratamos las aguas residuales del lavado de nuestras impresoras flexográficas, para reducir el agua utilizada y minimizar el impacto ambiental.",
     "We treat the wastewater from washing our flexographic printers, to reduce water use and minimize environmental impact.",
     "Tratamos as águas residuais da lavagem de nossas impressoras flexográficas, para reduzir a água utilizada e minimizar o impacto ambiental.",
     "Trattiamo le acque reflue del lavaggio delle nostre stampanti flessografiche, per ridurre l'acqua utilizzata e minimizzare l'impatto ambientale.",
     "Nous traitons les eaux usées issues du nettoyage de nos presses flexographiques, afin de réduire l'eau utilisée et de minimiser l'impact environnemental.",
     "Wir behandeln das Abwasser aus der Reinigung unserer Flexodruckmaschinen, um den Wasserverbrauch zu senken und die Umweltbelastung zu minimieren.",
     "我们对柔版印刷机清洗产生的废水进行处理，以减少用水量并最大限度地降低环境影响。"),
    ("Del diseño al reciclado", "Del diseño al reciclado", "From design to recycling", "Do design à reciclagem",
     "Dalla progettazione al riciclo", "De la conception au recyclage", "Vom Design zum Recycling", "从设计到回收"),
    ("Cada etapa está pensada para aprovechar mejor el material y darle una segunda vida.",
     "Cada etapa está pensada para aprovechar mejor el material y darle una segunda vida.",
     "Every stage is designed to make better use of material and give it a second life.",
     "Cada etapa é pensada para aproveitar melhor o material e dar a ele uma segunda vida.",
     "Ogni fase è pensata per sfruttare al meglio il materiale e dargli una seconda vita.",
     "Chaque étape est conçue pour mieux valoriser le matériau et lui donner une seconde vie.",
     "Jede Phase ist darauf ausgelegt, das Material besser zu nutzen und ihm ein zweites Leben zu geben.",
     "每个环节都旨在更好地利用材料，赋予其第二次生命。"),
    ("Diseño eficiente", "Diseño eficiente", "Efficient design", "Design eficiente", "Design efficiente",
     "Conception efficace", "Effizientes Design", "高效设计"),
    ("Moldes optimizados para usar menos material por unidad.", "Moldes optimizados para usar menos material por unidad.",
     "Molds optimized to use less material per unit.", "Moldes otimizados para usar menos material por unidade.",
     "Stampi ottimizzati per utilizzare meno materiale per unità.", "Moules optimisés pour utiliser moins de matériau par unité.",
     "Formen, optimiert für weniger Materialeinsatz pro Einheit.", "优化模具设计，降低单件材料用量。"),
    ("Control del consumo y aprovechamiento del papel.", "Control del consumo y aprovechamiento del papel.",
     "Control of paper consumption and use.", "Controle do consumo e aproveitamento do papel.",
     "Controllo del consumo e dell'utilizzo della carta.", "Contrôle de la consommation et de l'utilisation du papier.",
     "Kontrolle des Papierverbrauchs und der Papiernutzung.", "控制纸张消耗与使用效率。"),
    ("Recupero de scrap", "Recupero de scrap", "Scrap recovery", "Recuperação de aparas", "Recupero degli scarti",
     "Récupération des chutes", "Verschnittrückgewinnung", "边角料回收"),
    ("El recorte se separa y reingresa como recurso.", "El recorte se separa y reingresa como recurso.",
     "Trimmings are separated and reintroduced as a resource.", "A apara é separada e reintroduzida como recurso.",
     "Il ritaglio viene separato e reintrodotto come risorsa.", "Les chutes sont triées et réintroduites comme ressource.",
     "Der Verschnitt wird getrennt und als Ressource wiederverwendet.", "边角料经分类后重新用作资源。"),
    ("El papel es reciclable y biodegradable al final de su vida útil.", "El papel es reciclable y biodegradable al final de su vida útil.",
     "Paper is recyclable and biodegradable at the end of its useful life.", "O papel é reciclável e biodegradável ao final de sua vida útil.",
     "La carta è riciclabile e biodegradabile alla fine del suo ciclo di vita.", "Le papier est recyclable et biodégradable en fin de vie.",
     "Papier ist am Ende seiner Nutzungsdauer recycelbar und biologisch abbaubar.", "纸张在使用寿命结束后可回收并可生物降解。"),
    ("Nuestros compromisos", "Nuestros compromisos", "Our commitments", "Nossos compromissos", "I nostri impegni",
     "Nos engagements", "Unsere Verpflichtungen", "我们的承诺"),
    ("Cómo lo llevamos a la práctica", "Cómo lo llevamos a la práctica", "How we put it into practice",
     "Como colocamos isso em prática", "Come lo mettiamo in pratica", "Comment nous le mettons en pratique",
     "Wie wir es in die Praxis umsetzen", "我们如何付诸实践"),
    ("Materia prima renovable", "Materia prima renovable", "Renewable raw material", "Matéria-prima renovável",
     "Materia prima rinnovabile", "Matière première renouvelable", "Erneuerbarer Rohstoff", "可再生原材料"),
    ("Valorizamos el papel como recurso natural y renovable.", "Valorizamos el papel como recurso natural y renovable.",
     "We value paper as a natural, renewable resource.", "Valorizamos o papel como recurso natural e renovável.",
     "Valorizziamo la carta come risorsa naturale e rinnovabile.", "Nous valorisons le papier comme ressource naturelle et renouvelable.",
     "Wir schätzen Papier als natürliche, erneuerbare Ressource.", "我们重视纸张作为天然可再生资源的价值。"),
    ("Proveedores responsables", "Proveedores responsables", "Responsible suppliers", "Fornecedores responsáveis",
     "Fornitori responsabili", "Fournisseurs responsables", "Verantwortungsvolle Lieferanten", "负责任的供应商"),
    ("Manejo forestal certificado FSC, con autorizaciones ISEGA para contacto con alimentos.",
     "Manejo forestal certificado FSC, con autorizaciones ISEGA para contacto con alimentos.",
     "FSC-certified forest management, with ISEGA authorizations for food contact.",
     "Manejo florestal certificado FSC, com autorizações ISEGA para contato com alimentos.",
     "Gestione forestale certificata FSC, con autorizzazioni ISEGA per il contatto alimentare.",
     "Gestion forestière certifiée FSC, avec autorisations ISEGA pour le contact alimentaire.",
     "FSC-zertifizierte Waldbewirtschaftung, mit ISEGA-Zulassungen für Lebensmittelkontakt.",
     "通过FSC认证的森林管理，并持有ISEGA食品接触认证。"),
    ("Eficiencia de material", "Eficiencia de material", "Material efficiency", "Eficiência de material",
     "Efficienza dei materiali", "Efficacité des matériaux", "Materialeffizienz", "材料效率"),
    ("Diseños que reducen el desperdicio en origen.", "Diseños que reducen el desperdicio en origen.",
     "Designs that reduce waste at the source.", "Designs que reduzem o desperdício na origem.",
     "Design che riducono gli sprechi all'origine.", "Des conceptions qui réduisent le gaspillage à la source.",
     "Designs, die Abfall bereits an der Quelle reduzieren.", "从源头减少浪费的设计。"),
    ("Gestión de residuos", "Gestión de residuos", "Waste management", "Gestão de resíduos", "Gestione dei rifiuti",
     "Gestion des déchets", "Abfallmanagement", "废弃物管理"),
    ("Separación de papel, plásticos y lubricantes, con recicladoras externas.",
     "Separación de papel, plásticos y lubricantes, con recicladoras externas.",
     "Separation of paper, plastics and lubricants, with external recyclers.",
     "Separação de papel, plásticos e lubrificantes, com recicladoras externas.",
     "Separazione di carta, plastica e lubrificanti, con impianti di riciclaggio esterni.",
     "Tri du papier, des plastiques et des lubrifiants, avec des recycleurs externes.",
     "Trennung von Papier, Kunststoffen und Schmierstoffen mit externen Recyclingunternehmen.",
     "与外部回收企业合作，分类处理纸张、塑料和润滑油。"),
    ("Envases reciclables", "Envases reciclables", "Recyclable packaging", "Embalagens recicláveis",
     "Confezioni riciclabili", "Emballages recyclables", "Recycelbare Verpackungen", "可回收包装"),
    ("Productos pensados para su reciclado posterior.", "Productos pensados para su reciclado posterior.",
     "Products designed for later recycling.", "Produtos pensados para reciclagem posterior.",
     "Prodotti pensati per il successivo riciclo.", "Des produits conçus pour un recyclage ultérieur.",
     "Produkte, die für ein späteres Recycling konzipiert sind.", "产品设计考虑后续回收利用。"),
    ("Mejora continua", "Mejora continua", "Continuous improvement", "Melhoria contínua", "Miglioramento continuo",
     "Amélioration continue", "Kontinuierliche Verbesserung", "持续改进"),
    ("Revisamos procesos para reducir el impacto ambiental.", "Revisamos procesos para reducir el impacto ambiental.",
     "We review processes to reduce environmental impact.", "Revisamos processos para reduzir o impacto ambiental.",
     "Rivediamo i processi per ridurre l'impatto ambientale.", "Nous révisons nos processus pour réduire l'impact environnemental.",
     "Wir überprüfen Prozesse, um die Umweltbelastung zu reduzieren.", "我们持续审视流程以减少环境影响。"),
    ("Trabajemos de forma más sustentable", "Trabajemos de forma más sustentable", "Let's work more sustainably",
     "Vamos trabalhar de forma mais sustentável", "Lavoriamo in modo più sostenibile",
     "Travaillons de manière plus durable", "Lassen Sie uns nachhaltiger arbeiten", "让我们携手实现更可持续的发展"),
    ("Consultanos por soluciones de envase más eficientes para tu producción.",
     "Consultanos por soluciones de envase más eficientes para tu producción.",
     "Ask us about more efficient packaging solutions for your production.",
     "Consulte-nos sobre soluções de embalagem mais eficientes para sua produção.",
     "Contattaci per soluzioni di imballaggio più efficienti per la tua produzione.",
     "Contactez-nous pour des solutions d'emballage plus efficaces pour votre production.",
     "Fragen Sie uns nach effizienteren Verpackungslösungen für Ihre Produktion.",
     "欢迎咨询更适合您生产需求的高效包装解决方案。"),
    ("Contactanos", "Contactanos", "Contact us", "Fale conosco", "Contattaci", "Contactez-nous",
     "Kontaktieren Sie uns", "联系我们"),
]

bulk_translate(VIEW_ID, ROWS)
