# -*- coding: utf-8 -*-
from translate_helpers import bulk_translate

VIEW_ID = 1444  # calidad_template

ROWS = [
    ("Calidad y certificaciones — Cartotécnica Hores", "Calidad y certificaciones — Cartotécnica Hores",
     "Quality and certifications — Cartotécnica Hores", "Qualidade e certificações — Cartotécnica Hores",
     "Qualità e certificazioni — Cartotécnica Hores", "Qualité et certifications — Cartotécnica Hores",
     "Qualität und Zertifizierungen — Cartotécnica Hores", "品质与认证 — Cartotécnica Hores"),
    ("Gestión de inocuidad certificada ISO 22000:2018. Moldes de papel aptos para contacto directo con alimentos, con control de calidad en cada etapa de producción.",
     "Gestión de inocuidad certificada ISO 22000:2018. Moldes de papel aptos para contacto directo con alimentos, con control de calidad en cada etapa de producción.",
     "Food-safety management certified to ISO 22000:2018. Paper molds suitable for direct food contact, with quality control at every stage of production.",
     "Gestão de inocuidade certificada ISO 22000:2018. Moldes de papel próprios para contato direto com alimentos, com controle de qualidade em cada etapa da produção.",
     "Gestione della sicurezza alimentare certificata ISO 22000:2018. Stampi di carta adatti al contatto diretto con gli alimenti, con controllo qualità in ogni fase della produzione.",
     "Gestion de la sécurité alimentaire certifiée ISO 22000:2018. Moules en papier adaptés au contact direct avec les aliments, avec un contrôle qualité à chaque étape de la production.",
     "Zertifiziertes Lebensmittelsicherheitsmanagement ISO 22000:2018. Papierformen für direkten Lebensmittelkontakt geeignet, mit Qualitätskontrolle in jeder Produktionsphase.",
     "通过ISO 22000:2018认证的食品安全管理体系。适合直接接触食品的纸模，生产各环节均实施质量控制。"),
    ("Inicio", "Inicio", "Home", "Início", "Home", "Accueil", "Startseite", "首页"),
    ('<span style="opacity:.6;">/</span> Calidad', '<span style="opacity:.6;">/</span> Calidad',
     '<span style="opacity:.6;">/</span> Quality', '<span style="opacity:.6;">/</span> Qualidade',
     '<span style="opacity:.6;">/</span> Qualità', '<span style="opacity:.6;">/</span> Qualité',
     '<span style="opacity:.6;">/</span> Qualität', '<span style="opacity:.6;">/</span> 品质'),
    ('<span style="width:26px; height:2px; background:#c26a1e; display:inline-block;"/> Calidad y certificaciones',
     '<span style="width:26px; height:2px; background:#c26a1e; display:inline-block;"/> Calidad y certificaciones',
     '<span style="width:26px; height:2px; background:#c26a1e; display:inline-block;"/> Quality and certifications',
     '<span style="width:26px; height:2px; background:#c26a1e; display:inline-block;"/> Qualidade e certificações',
     '<span style="width:26px; height:2px; background:#c26a1e; display:inline-block;"/> Qualità e certificazioni',
     '<span style="width:26px; height:2px; background:#c26a1e; display:inline-block;"/> Qualité et certifications',
     '<span style="width:26px; height:2px; background:#c26a1e; display:inline-block;"/> Qualität und Zertifizierungen',
     '<span style="width:26px; height:2px; background:#c26a1e; display:inline-block;"/> 品质与认证'),
    ("Inocuidad controlada en cada etapa", "Inocuidad controlada en cada etapa",
     "Food safety controlled at every stage", "Inocuidade controlada em cada etapa",
     "Sicurezza alimentare controllata in ogni fase", "Sécurité alimentaire contrôlée à chaque étape",
     "Lebensmittelsicherheit in jeder Phase kontrolliert", "全流程食品安全管控"),
    ("Todos nuestros productos están autorizados para el contacto directo con alimentos y se fabrican bajo un sistema de gestión de inocuidad certificado según norma ISO 22000:2018.",
     "Todos nuestros productos están autorizados para el contacto directo con alimentos y se fabrican bajo un sistema de gestión de inocuidad certificado según norma ISO 22000:2018.",
     "All our products are approved for direct food contact and are manufactured under a food-safety management system certified to ISO 22000:2018.",
     "Todos os nossos produtos são autorizados para contato direto com alimentos e fabricados sob um sistema de gestão de inocuidade certificado conforme a norma ISO 22000:2018.",
     "Tutti i nostri prodotti sono autorizzati al contatto diretto con gli alimenti e vengono fabbricati nell'ambito di un sistema di gestione della sicurezza alimentare certificato secondo la norma ISO 22000:2018.",
     "Tous nos produits sont autorisés au contact direct avec les aliments et fabriqués dans le cadre d'un système de gestion de la sécurité alimentaire certifié selon la norme ISO 22000:2018.",
     "Alle unsere Produkte sind für den direkten Lebensmittelkontakt zugelassen und werden im Rahmen eines nach ISO 22000:2018 zertifizierten Lebensmittelsicherheitsmanagementsystems hergestellt.",
     "我们所有产品均获准直接接触食品，并在通过ISO 22000:2018认证的食品安全管理体系下生产。"),
    ('<span style="width:34px; height:34px; border-radius:8px; background:#c26a1e; color:#fff; display:flex; align-items:center; justify-content:center; font-family:\'Source Serif 4\',serif; font-weight:700;">✓</span>\n                <span style="font-size:14px; color:#4a4f54;"><strong style="color:#1c2124;">ISO 22000:2018</strong> — Gestión de inocuidad certificada</span>',
     '<span style="width:34px; height:34px; border-radius:8px; background:#c26a1e; color:#fff; display:flex; align-items:center; justify-content:center; font-family:\'Source Serif 4\',serif; font-weight:700;">✓</span>\n                <span style="font-size:14px; color:#4a4f54;"><strong style="color:#1c2124;">ISO 22000:2018</strong> — Gestión de inocuidad certificada</span>',
     '<span style="width:34px; height:34px; border-radius:8px; background:#c26a1e; color:#fff; display:flex; align-items:center; justify-content:center; font-family:\'Source Serif 4\',serif; font-weight:700;">✓</span>\n                <span style="font-size:14px; color:#4a4f54;"><strong style="color:#1c2124;">ISO 22000:2018</strong> — Certified food-safety management</span>',
     '<span style="width:34px; height:34px; border-radius:8px; background:#c26a1e; color:#fff; display:flex; align-items:center; justify-content:center; font-family:\'Source Serif 4\',serif; font-weight:700;">✓</span>\n                <span style="font-size:14px; color:#4a4f54;"><strong style="color:#1c2124;">ISO 22000:2018</strong> — Gestão de inocuidade certificada</span>',
     '<span style="width:34px; height:34px; border-radius:8px; background:#c26a1e; color:#fff; display:flex; align-items:center; justify-content:center; font-family:\'Source Serif 4\',serif; font-weight:700;">✓</span>\n                <span style="font-size:14px; color:#4a4f54;"><strong style="color:#1c2124;">ISO 22000:2018</strong> — Gestione della sicurezza alimentare certificata</span>',
     '<span style="width:34px; height:34px; border-radius:8px; background:#c26a1e; color:#fff; display:flex; align-items:center; justify-content:center; font-family:\'Source Serif 4\',serif; font-weight:700;">✓</span>\n                <span style="font-size:14px; color:#4a4f54;"><strong style="color:#1c2124;">ISO 22000:2018</strong> — Gestion de la sécurité alimentaire certifiée</span>',
     '<span style="width:34px; height:34px; border-radius:8px; background:#c26a1e; color:#fff; display:flex; align-items:center; justify-content:center; font-family:\'Source Serif 4\',serif; font-weight:700;">✓</span>\n                <span style="font-size:14px; color:#4a4f54;"><strong style="color:#1c2124;">ISO 22000:2018</strong> — Zertifiziertes Lebensmittelsicherheitsmanagement</span>',
     '<span style="width:34px; height:34px; border-radius:8px; background:#c26a1e; color:#fff; display:flex; align-items:center; justify-content:center; font-family:\'Source Serif 4\',serif; font-weight:700;">✓</span>\n                <span style="font-size:14px; color:#4a4f54;"><strong style="color:#1c2124;">ISO 22000:2018</strong> — 认证食品安全管理体系</span>'),
    ("Control de calidad en planta Cartotécnica Hores — inspección de lotes",
     "Control de calidad en planta Cartotécnica Hores — inspección de lotes",
     "Quality control at the Cartotécnica Hores plant — batch inspection",
     "Controle de qualidade na fábrica Cartotécnica Hores — inspeção de lotes",
     "Controllo qualità nello stabilimento Cartotécnica Hores — ispezione dei lotti",
     "Contrôle qualité à l'usine Cartotécnica Hores — inspection des lots",
     "Qualitätskontrolle im Werk Cartotécnica Hores — Chargenprüfung",
     "Cartotécnica Hores 工厂质量控制 — 批次检验"),
    ("Gestión de inocuidad certificada (2018)", "Gestión de inocuidad certificada (2018)",
     "Certified food-safety management (2018)", "Gestão de inocuidade certificada (2018)",
     "Gestione della sicurezza alimentare certificata (2018)", "Gestion de la sécurité alimentaire certifiée (2018)",
     "Zertifiziertes Lebensmittelsicherheitsmanagement (2018)", "认证食品安全管理体系（2018年）"),
    ("Productos aptos para contacto con alimentos", "Productos aptos para contacto con alimentos",
     "Products suitable for food contact", "Produtos próprios para contato com alimentos",
     "Prodotti idonei al contatto alimentare", "Produits adaptés au contact alimentaire",
     "Für Lebensmittelkontakt geeignete Produkte", "适合接触食品的产品"),
    ("Trazable", "Trazable", "Traceable", "Rastreável", "Tracciabile", "Traçable", "Rückverfolgbar", "可追溯"),
    ("Control de lote y materia prima", "Control de lote y materia prima", "Batch and raw-material control",
     "Controle de lote e matéria-prima", "Controllo di lotto e materia prima",
     "Contrôle des lots et des matières premières", "Chargen- und Rohstoffkontrolle", "批次与原料管控"),
    ("Inocuidad alimentaria", "Inocuidad alimentaria", "Food safety", "Inocuidade alimentar",
     "Sicurezza alimentare", "Sécurité alimentaire", "Lebensmittelsicherheit", "食品安全"),
    ("Materiales aptos, procesos trazables", "Materiales aptos, procesos trazables",
     "Suitable materials, traceable processes", "Materiais próprios, processos rastreáveis",
     "Materiali idonei, processi tracciabili", "Matériaux adaptés, processus traçables",
     "Geeignete Materialien, rückverfolgbare Prozesse", "合规材料，全程可追溯"),
    ("Trabajamos con materiales aptos para uso alimentario y controlamos la trazabilidad de la materia prima. Cada lote se produce siguiendo procedimientos documentados que garantizan condiciones seguras de higiene y manipulación.",
     "Trabajamos con materiales aptos para uso alimentario y controlamos la trazabilidad de la materia prima. Cada lote se produce siguiendo procedimientos documentados que garantizan condiciones seguras de higiene y manipulación.",
     "We work with materials suitable for food use and control the traceability of raw materials. Each batch is produced following documented procedures that guarantee safe hygiene and handling conditions.",
     "Trabalhamos com materiais próprios para uso alimentar e controlamos a rastreabilidade da matéria-prima. Cada lote é produzido seguindo procedimentos documentados que garantem condições seguras de higiene e manuseio.",
     "Lavoriamo con materiali idonei all'uso alimentare e controlliamo la tracciabilità della materia prima. Ogni lotto viene prodotto seguendo procedure documentate che garantiscono condizioni sicure di igiene e manipolazione.",
     "Nous travaillons avec des matériaux adaptés à un usage alimentaire et contrôlons la traçabilité des matières premières. Chaque lot est produit selon des procédures documentées garantissant des conditions d'hygiène et de manipulation sûres.",
     "Wir arbeiten mit für den Lebensmittelgebrauch geeigneten Materialien und kontrollieren die Rückverfolgbarkeit der Rohstoffe. Jede Charge wird nach dokumentierten Verfahren hergestellt, die sichere Hygiene- und Handhabungsbedingungen gewährleisten.",
     "我们使用符合食品用途要求的材料，并对原材料进行可追溯管控。每批产品均按照书面规程生产，确保卫生和操作条件安全。"),
    ("La gestión de inocuidad certificada ISO 22000:2018 ordena todos nuestros procesos: desde la recepción de insumos hasta el despacho del producto terminado.",
     "La gestión de inocuidad certificada ISO 22000:2018 ordena todos nuestros procesos: desde la recepción de insumos hasta el despacho del producto terminado.",
     "Our ISO 22000:2018 certified food-safety management governs all our processes: from receiving supplies to shipping the finished product.",
     "A gestão de inocuidade certificada ISO 22000:2018 organiza todos os nossos processos: desde o recebimento de insumos até o despacho do produto acabado.",
     "La gestione della sicurezza alimentare certificata ISO 22000:2018 governa tutti i nostri processi: dal ricevimento delle materie prime alla spedizione del prodotto finito.",
     "La gestion de la sécurité alimentaire certifiée ISO 22000:2018 régit tous nos processus : de la réception des matières premières à l'expédition du produit fini.",
     "Das nach ISO 22000:2018 zertifizierte Lebensmittelsicherheitsmanagement steuert alle unsere Prozesse: vom Wareneingang bis zum Versand des fertigen Produkts.",
     "通过ISO 22000:2018认证的食品安全管理体系贯穿我们所有流程：从原料接收到成品发货。"),
    ("Materia prima apta", "Materia prima apta", "Suitable raw material", "Matéria-prima própria",
     "Materia prima idonea", "Matière première adaptée", "Geeigneter Rohstoff", "合规原料"),
    ("Insumos habilitados para contacto con alimentos.", "Insumos habilitados para contacto con alimentos.",
     "Supplies approved for food contact.", "Insumos habilitados para contato com alimentos.",
     "Materiali abilitati al contatto alimentare.", "Fournitures autorisées au contact alimentaire.",
     "Für Lebensmittelkontakt zugelassene Materialien.", "获准接触食品的原料。"),
    ("Higiene en planta", "Higiene en planta", "Plant hygiene", "Higiene na fábrica", "Igiene in stabilimento",
     "Hygiène en usine", "Werkshygiene", "厂区卫生"),
    ("Procedimientos de limpieza y manipulación documentados.", "Procedimientos de limpieza y manipulación documentados.",
     "Documented cleaning and handling procedures.", "Procedimentos de limpeza e manuseio documentados.",
     "Procedure di pulizia e manipolazione documentate.", "Procédures de nettoyage et de manipulation documentées.",
     "Dokumentierte Reinigungs- und Handhabungsverfahren.", "有据可查的清洁与操作规程。"),
    ("Control por lote", "Control por lote", "Batch control", "Controle por lote", "Controllo per lotto",
     "Contrôle par lot", "Chargenkontrolle", "批次控制"),
    ("Verificación de medidas y materiales en cada producción.", "Verificación de medidas y materiales en cada producción.",
     "Verification of measurements and materials in every production run.", "Verificação de medidas e materiais em cada produção.",
     "Verifica di misure e materiali in ogni produzione.", "Vérification des dimensions et des matériaux à chaque production.",
     "Überprüfung von Maßen und Materialien bei jeder Produktion.", "每批生产均核验尺寸与材料。"),
    ("Trazabilidad", "Trazabilidad", "Traceability", "Rastreabilidade", "Tracciabilità", "Traçabilité",
     "Rückverfolgbarkeit", "可追溯性"),
    ("Registro desde la recepción hasta el despacho.", "Registro desde la recepción hasta el despacho.",
     "Record-keeping from receiving through shipping.", "Registro desde o recebimento até o despacho.",
     "Registrazione dalla ricezione alla spedizione.", "Enregistrement de la réception à l'expédition.",
     "Erfassung vom Wareneingang bis zum Versand.", "从接收到发货全程记录。"),
    ("Política de inocuidad", "Política de inocuidad", "Food-safety policy", "Política de inocuidade",
     "Politica di sicurezza alimentare", "Politique de sécurité alimentaire", "Lebensmittelsicherheitspolitik", "食品安全方针"),
    ("Nuestros objetivos prioritarios", "Nuestros objetivos prioritarios", "Our priority objectives",
     "Nossos objetivos prioritários", "I nostri obiettivi prioritari", "Nos objectifs prioritaires",
     "Unsere vorrangigen Ziele", "我们的优先目标"),
    ("Productos inocuos, a través del control de nuestros procesos.", "Productos inocuos, a través del control de nuestros procesos.",
     "Safe products, through control of our processes.", "Produtos inócuos, por meio do controle de nossos processos.",
     "Prodotti sicuri, attraverso il controllo dei nostri processi.", "Des produits sûrs, grâce au contrôle de nos processus.",
     "Sichere Produkte durch die Kontrolle unserer Prozesse.", "通过流程管控确保产品安全。"),
    ("Cumplimiento de los requisitos legales, reglamentarios y de nuestros clientes.",
     "Cumplimiento de los requisitos legales, reglamentarios y de nuestros clientes.",
     "Compliance with legal, regulatory and customer requirements.",
     "Cumprimento dos requisitos legais, regulamentares e de nossos clientes.",
     "Conformità ai requisiti legali, normativi e dei nostri clienti.",
     "Conformité aux exigences légales, réglementaires et de nos clients.",
     "Einhaltung gesetzlicher, behördlicher und kundenseitiger Anforderungen.",
     "遵守法律法规及客户要求。"),
    ("Eficacia y mejora continua en cada uno de nuestros procesos.", "Eficacia y mejora continua en cada uno de nuestros procesos.",
     "Effectiveness and continuous improvement in each of our processes.", "Eficácia e melhoria contínua em cada um de nossos processos.",
     "Efficacia e miglioramento continuo in ciascuno dei nostri processi.", "Efficacité et amélioration continue de chacun de nos processus.",
     "Wirksamkeit und kontinuierliche Verbesserung all unserer Prozesse.", "各流程的有效性与持续改进。"),
    ("Un ambiente laboral seguro, con nuestro equipo comprometido con el sistema de gestión.",
     "Un ambiente laboral seguro, con nuestro equipo comprometido con el sistema de gestión.",
     "A safe work environment, with our team committed to the management system.",
     "Um ambiente de trabalho seguro, com nossa equipe comprometida com o sistema de gestão.",
     "Un ambiente di lavoro sicuro, con il nostro team impegnato nel sistema di gestione.",
     "Un environnement de travail sûr, avec notre équipe engagée envers le système de gestion.",
     "Ein sicheres Arbeitsumfeld mit einem Team, das sich dem Managementsystem verpflichtet fühlt.",
     "安全的工作环境，团队全力支持管理体系。"),
    ("Nuestro proceso", "Nuestro proceso", "Our process", "Nosso processo", "Il nostro processo",
     "Notre processus", "Unser Prozess", "我们的流程"),
    ("Control en cada etapa", "Control en cada etapa", "Control at every stage", "Controle em cada etapa",
     "Controllo in ogni fase", "Contrôle à chaque étape", "Kontrolle in jeder Phase", "每个环节都受控"),
    ("Un sistema documentado que asegura la misma calidad en cada lote.", "Un sistema documentado que asegura la misma calidad en cada lote.",
     "A documented system that ensures the same quality in every batch.", "Um sistema documentado que garante a mesma qualidade em cada lote.",
     "Un sistema documentato che garantisce la stessa qualità in ogni lotto.", "Un système documenté qui garantit la même qualité à chaque lot.",
     "Ein dokumentiertes System, das in jeder Charge die gleiche Qualität sicherstellt.", "有据可查的体系确保每批产品品质如一。"),
    ("Recepción de insumos", "Recepción de insumos", "Receiving supplies", "Recebimento de insumos",
     "Ricevimento delle materie prime", "Réception des matières premières", "Wareneingang", "原料接收"),
    ("Control de proveedores y materia prima apta.", "Control de proveedores y materia prima apta.",
     "Supplier control and suitable raw materials.", "Controle de fornecedores e matéria-prima própria.",
     "Controllo dei fornitori e materia prima idonea.", "Contrôle des fournisseurs et matières premières adaptées.",
     "Lieferantenkontrolle und geeignete Rohstoffe.", "供应商管控与合规原料。"),
    ("Producción", "Producción", "Production", "Produção", "Produzione", "Production", "Produktion", "生产"),
    ("Higiene y manipulación bajo procedimientos.", "Higiene y manipulación bajo procedimientos.",
     "Hygiene and handling under procedures.", "Higiene e manuseio sob procedimentos.",
     "Igiene e manipolazione secondo procedure.", "Hygiène et manipulation selon des procédures.",
     "Hygiene und Handhabung nach festgelegten Verfahren.", "依规程进行卫生与操作管理。"),
    ("Control de calidad", "Control de calidad", "Quality control", "Controle de qualidade", "Controllo qualità",
     "Contrôle qualité", "Qualitätskontrolle", "质量控制"),
    ("Verificación por lote de medidas y materiales.", "Verificación por lote de medidas y materiales.",
     "Per-batch verification of measurements and materials.", "Verificação por lote de medidas e materiais.",
     "Verifica per lotto di misure e materiali.", "Vérification par lot des dimensions et matériaux.",
     "Chargenweise Prüfung von Maßen und Materialien.", "按批次核验尺寸与材料。"),
    ("Despacho", "Despacho", "Shipping", "Despacho", "Spedizione", "Expédition", "Versand", "发货"),
    ("Trazabilidad hasta la entrega del producto.", "Trazabilidad hasta la entrega del producto.",
     "Traceability through product delivery.", "Rastreabilidade até a entrega do produto.",
     "Tracciabilità fino alla consegna del prodotto.", "Traçabilité jusqu'à la livraison du produit.",
     "Rückverfolgbarkeit bis zur Produktlieferung.", "全程可追溯直至产品交付。"),
    ("Certificaciones", "Certificaciones", "Certifications", "Certificações", "Certificazioni", "Certifications",
     "Zertifizierungen", "认证"),
    ("Documentación disponible", "Documentación disponible", "Documentation available", "Documentação disponível",
     "Documentazione disponibile", "Documentation disponible", "Verfügbare Dokumentation", "可提供文件"),
    ("Solicitá los certificados y fichas técnicas que necesites para tu proceso.", "Solicitá los certificados y fichas técnicas que necesites para tu proceso.",
     "Request the certificates and spec sheets you need for your process.", "Solicite os certificados e fichas técnicas que precisar para o seu processo.",
     "Richiedi i certificati e le schede tecniche di cui hai bisogno per il tuo processo.", "Demandez les certificats et fiches techniques dont vous avez besoin pour votre processus.",
     "Fordern Sie die Zertifikate und Datenblätter an, die Sie für Ihren Prozess benötigen.", "如需相关证书或技术规格表，请与我们联系索取。"),
    ("Certificado ISO 22000:2018", "Certificado ISO 22000:2018", "ISO 22000:2018 Certificate", "Certificado ISO 22000:2018",
     "Certificato ISO 22000:2018", "Certificat ISO 22000:2018", "Zertifikat ISO 22000:2018", "ISO 22000:2018 证书"),
    ("Sistema de gestión de inocuidad de los alimentos vigente.", "Sistema de gestión de inocuidad de los alimentos vigente.",
     "Current food-safety management system.", "Sistema de gestão de inocuidade de alimentos vigente.",
     "Sistema di gestione della sicurezza alimentare in vigore.", "Système de gestion de la sécurité alimentaire en vigueur.",
     "Aktuell gültiges Lebensmittelsicherheitsmanagementsystem.", "现行有效的食品安全管理体系。"),
    ("Solicitar por email →", "Solicitar por email →", "Request by email →", "Solicitar por email →",
     "Richiedi via email →", "Demander par email →", "Per E-Mail anfordern →", "通过邮件申请 →"),
    ("Aptitud sanitaria", "Aptitud sanitaria", "Sanitary approval", "Aptidão sanitária", "Idoneità sanitaria",
     "Aptitude sanitaire", "Gesundheitliche Eignung", "卫生合格认证"),
    ("Documentación que acredita el uso en contacto con alimentos.", "Documentación que acredita el uso en contacto con alimentos.",
     "Documentation certifying use in food contact.", "Documentação que comprova o uso em contato com alimentos.",
     "Documentazione che attesta l'uso a contatto con gli alimenti.", "Documentation attestant l'utilisation au contact alimentaire.",
     "Dokumentation, die den Einsatz im Lebensmittelkontakt bestätigt.", "证明产品可用于接触食品的文件。"),
    ("Fichas técnicas", "Fichas técnicas", "Spec sheets", "Fichas técnicas", "Schede tecniche", "Fiches techniques",
     "Datenblätter", "技术规格表"),
    ("Especificaciones de cada producto: medidas, gramaje y material.", "Especificaciones de cada producto: medidas, gramaje y material.",
     "Specifications for each product: measurements, weight and material.", "Especificações de cada produto: medidas, gramatura e material.",
     "Specifiche di ogni prodotto: misure, grammatura e materiale.", "Spécifications de chaque produit : dimensions, grammage et matériau.",
     "Spezifikationen jedes Produkts: Maße, Gewicht und Material.", "各产品规格：尺寸、克重与材质。"),
    ("Ver catálogo →", "Ver catálogo →", "View catalog →", "Ver catálogo →", "Vedi catalogo →", "Voir le catalogue →",
     "Katalog ansehen →", "查看目录 →"),
    ("¿Necesitás la documentación de calidad?", "¿Necesitás la documentación de calidad?", "Need quality documentation?",
     "Precisa da documentação de qualidade?", "Hai bisogno della documentazione sulla qualità?",
     "Besoin de la documentation qualité ?", "Benötigen Sie Qualitätsdokumente?", "需要品质相关文件吗？"),
    ("Escribinos y te enviamos los certificados y fichas técnicas correspondientes.", "Escribinos y te enviamos los certificados y fichas técnicas correspondientes.",
     "Write to us and we'll send you the corresponding certificates and spec sheets.", "Escreva para nós e enviaremos os certificados e fichas técnicas correspondentes.",
     "Scrivici e ti invieremo i certificati e le schede tecniche corrispondenti.", "Écrivez-nous et nous vous enverrons les certificats et fiches techniques correspondants.",
     "Schreiben Sie uns, und wir senden Ihnen die entsprechenden Zertifikate und Datenblätter zu.", "联系我们，我们会将相应的证书和技术规格表发送给您。"),
    ("Solicitar documentación", "Solicitar documentación", "Request documentation", "Solicitar documentação",
     "Richiedi documentazione", "Demander la documentation", "Dokumentation anfordern", "申请文件"),
]

bulk_translate(VIEW_ID, ROWS)
