# -*- coding: utf-8 -*-
from translate_helpers import bulk_translate

VIEW_ID = 1445  # historia_template

ROWS = [
    ("Nuestra historia — Cartotécnica Hores", "Nuestra historia — Cartotécnica Hores",
     "Our history — Cartotécnica Hores", "Nossa história — Cartotécnica Hores",
     "La nostra storia — Cartotécnica Hores", "Notre histoire — Cartotécnica Hores",
     "Unsere Geschichte — Cartotécnica Hores", "我们的历史 — Cartotécnica Hores"),
    ("Más de 30 años fabricando moldes de papel para panificación en Bell Ville, Córdoba. Conocé nuestra trayectoria, valores y objetivos.",
     "Más de 30 años fabricando moldes de papel para panificación en Bell Ville, Córdoba. Conocé nuestra trayectoria, valores y objetivos.",
     "More than 30 years manufacturing paper molds for baking in Bell Ville, Córdoba. Discover our history, values and goals.",
     "Mais de 30 anos fabricando moldes de papel para panificação em Bell Ville, Córdoba. Conheça nossa trajetória, valores e objetivos.",
     "Oltre 30 anni di produzione di stampi di carta per la panificazione a Bell Ville, Córdoba. Scopri il nostro percorso, i nostri valori e i nostri obiettivi.",
     "Plus de 30 ans de fabrication de moules en papier pour la boulangerie à Bell Ville, Córdoba. Découvrez notre parcours, nos valeurs et nos objectifs.",
     "Seit mehr als 30 Jahren fertigen wir Papierformen für die Bäckerei in Bell Ville, Córdoba. Entdecken Sie unsere Geschichte, Werte und Ziele.",
     "30多年来，我们始终在科尔多瓦贝尔维尔生产烘焙用纸模。了解我们的发展历程、价值观和目标。"),
    ("Cambiar tema claro/oscuro", "Cambiar tema claro/oscuro", "Switch light/dark theme",
     "Alternar tema claro/escuro", "Cambia tema chiaro/scuro", "Changer de thème clair/sombre",
     "Hell-/Dunkelmodus wechseln", "切换浅色/深色主题"),
    ('<span style="width:26px; height:2px; background:#f0b878; display:inline-block;"/> Nuestra historia <span style="width:26px; height:2px; background:#f0b878; display:inline-block;"/>',
     '<span style="width:26px; height:2px; background:#f0b878; display:inline-block;"/> Nuestra historia <span style="width:26px; height:2px; background:#f0b878; display:inline-block;"/>',
     '<span style="width:26px; height:2px; background:#f0b878; display:inline-block;"/> Our history <span style="width:26px; height:2px; background:#f0b878; display:inline-block;"/>',
     '<span style="width:26px; height:2px; background:#f0b878; display:inline-block;"/> Nossa história <span style="width:26px; height:2px; background:#f0b878; display:inline-block;"/>',
     '<span style="width:26px; height:2px; background:#f0b878; display:inline-block;"/> La nostra storia <span style="width:26px; height:2px; background:#f0b878; display:inline-block;"/>',
     '<span style="width:26px; height:2px; background:#f0b878; display:inline-block;"/> Notre histoire <span style="width:26px; height:2px; background:#f0b878; display:inline-block;"/>',
     '<span style="width:26px; height:2px; background:#f0b878; display:inline-block;"/> Unsere Geschichte <span style="width:26px; height:2px; background:#f0b878; display:inline-block;"/>',
     '<span style="width:26px; height:2px; background:#f0b878; display:inline-block;"/> 我们的历史 <span style="width:26px; height:2px; background:#f0b878; display:inline-block;"/>'),
    ('Más de 30 años construyendo <span style="color:#e08a34;">confianza</span>',
     'Más de 30 años construyendo <span style="color:#e08a34;">confianza</span>',
     'More than 30 years building <span style="color:#e08a34;">trust</span>',
     'Mais de 30 anos construindo <span style="color:#e08a34;">confiança</span>',
     'Oltre 30 anni costruendo <span style="color:#e08a34;">fiducia</span>',
     'Plus de 30 ans à bâtir la <span style="color:#e08a34;">confiance</span>',
     'Seit über 30 Jahren bauen wir <span style="color:#e08a34;">Vertrauen</span> auf',
     '30多年来，我们始终在建立<span style="color:#e08a34;">信任</span>'),
    ("Desde Bell Ville, Córdoba, hasta el resto de la región: así fuimos creciendo, molde a molde.",
     "Desde Bell Ville, Córdoba, hasta el resto de la región: así fuimos creciendo, molde a molde.",
     "From Bell Ville, Córdoba, to the rest of the region: this is how we grew, mold by mold.",
     "De Bell Ville, Córdoba, até o resto da região: assim fomos crescendo, molde a molde.",
     "Da Bell Ville, Córdoba, al resto della regione: così siamo cresciuti, stampo dopo stampo.",
     "De Bell Ville, Córdoba, jusqu'au reste de la région : c'est ainsi que nous avons grandi, moule après moule.",
     "Von Bell Ville, Córdoba, bis in den Rest der Region: So sind wir gewachsen, Form für Form.",
     "从科尔多瓦贝尔维尔到整个地区：我们就是这样一步一个模具地成长起来的。"),
    ("Recorrido", "Recorrido", "Journey", "Trajetória", "Percorso", "Parcours", "Werdegang", "历程"),
    ("Nuestro camino", "Nuestro camino", "Our path", "Nosso caminho", "Il nostro cammino", "Notre chemin",
     "Unser Weg", "我们的道路"),
    ("Cómo trabajamos", "Cómo trabajamos", "How we work", "Como trabalhamos", "Come lavoriamo",
     "Comment nous travaillons", "Wie wir arbeiten", "我们的工作方式"),
    ("Nuestros valores", "Nuestros valores", "Our values", "Nossos valores", "I nostri valori",
     "Nos valeurs", "Unsere Werte", "我们的价值观"),
    ("Producción", "Producción", "Production", "Produção", "Produzione", "Production", "Produktion", "生产"),
    ("Nuestras líneas de producto", "Nuestras líneas de producto", "Our product lines", "Nossas linhas de produto",
     "Le nostre linee di prodotto", "Nos gammes de produits", "Unsere Produktlinien", "我们的产品线"),
    ("Por qué nos eligen", "Por qué nos eligen", "Why they choose us", "Por que nos escolhem",
     "Perché ci scelgono", "Pourquoi ils nous choisissent", "Warum man sich für uns entscheidet", "为什么选择我们"),
    ("Confían en nosotros", "Confían en nosotros", "They trust us", "Confiam em nós", "Si fidano di noi",
     "Ils nous font confiance", "Sie vertrauen uns", "客户对我们的信任"),
    ("Clientes destacados", "Clientes destacados", "Featured clients", "Clientes em destaque",
     "Clienti in evidenza", "Clients phares", "Ausgewählte Kunden", "重点客户"),
    ("Ejemplos ilustrativos — se reemplazan por clientes reales antes de publicar.",
     "Ejemplos ilustrativos — se reemplazan por clientes reales antes de publicar.",
     "Illustrative examples — to be replaced with real clients before publishing.",
     "Exemplos ilustrativos — serão substituídos por clientes reais antes da publicação.",
     "Esempi illustrativi — verranno sostituiti con clienti reali prima della pubblicazione.",
     "Exemples illustratifs — à remplacer par de vrais clients avant publication.",
     "Illustrative Beispiele — werden vor der Veröffentlichung durch echte Kunden ersetzt.",
     "示例内容 — 发布前将替换为真实客户信息。"),
    ("Alcance regional", "Alcance regional", "Regional reach", "Alcance regional", "Portata regionale",
     "Portée régionale", "Regionale Reichweite", "区域覆盖"),
    ("Presencia geográfica", "Presencia geográfica", "Geographic presence", "Presença geográfica",
     "Presenza geografica", "Présence géographique", "Geografische Präsenz", "地理覆盖"),
    ("Mirando adelante", "Mirando adelante", "Looking ahead", "Olhando para o futuro", "Guardando avanti",
     "Regard vers l'avenir", "Blick nach vorn", "展望未来"),
    ("Objetivos", "Objetivos", "Goals", "Objetivos", "Obiettivi", "Objectifs", "Ziele", "目标"),
    ("Volver al sitio →", "Volver al sitio →", "Back to site →", "Voltar ao site →", "Torna al sito →",
     "Retour au site →", "Zurück zur Website →", "返回网站 →"),
    ("Volver arriba", "Volver arriba", "Back to top", "Voltar ao topo", "Torna su", "Retour en haut",
     "Nach oben", "返回顶部"),
]

bulk_translate(VIEW_ID, ROWS)
