# -*- coding: utf-8 -*-
from translate_helpers import bulk_translate

VIEW_ID = 2238  # pedido_gestionar_template

ROWS = [
    ("Pedido", "Pedido", "Order", "Pedido", "Ordine", "Commande", "Bestellung", "订单"),
    ("— Cartotecnica Hores", "— Cartotecnica Hores", "— Cartotecnica Hores", "— Cartotecnica Hores",
     "— Cartotecnica Hores", "— Cartotecnica Hores", "— Cartotecnica Hores", "— Cartotecnica Hores"),
    ("Cancelado", "Cancelado", "Cancelled", "Cancelado", "Annullato", "Annulée", "Storniert", "已取消"),
    ("Presupuesto", "Presupuesto", "Quote", "Orçamento", "Preventivo", "Devis", "Angebot", "报价单"),
    ("Confirmado", "Confirmado", "Confirmed", "Confirmado", "Confermato", "Confirmée", "Bestätigt", "已确认"),
    ("Listo, cancelamos tu pedido.", "Listo, cancelamos tu pedido.", "Done, we cancelled your order.",
     "Pronto, cancelamos seu pedido.", "Fatto, abbiamo annullato il tuo ordine.",
     "C'est fait, nous avons annulé votre commande.", "Erledigt, wir haben Ihre Bestellung storniert.",
     "好的，您的订单已取消。"),
    ("Recibimos tu pedido de cambio — te vamos a contactar a la brevedad.",
     "Recibimos tu pedido de cambio — te vamos a contactar a la brevedad.",
     "We received your change request — we'll contact you shortly.",
     "Recebemos seu pedido de alteração — entraremos em contato em breve.",
     "Abbiamo ricevuto la tua richiesta di modifica — ti contatteremo a breve.",
     "Nous avons reçu votre demande de modification — nous vous contacterons rapidement.",
     "Wir haben Ihre Änderungsanfrage erhalten — wir melden uns in Kürze.",
     "我们已收到您的变更请求 — 将尽快与您联系。"),
    ("Productos", "Productos", "Products", "Produtos", "Prodotti", "Produits", "Produkte", "产品"),
    ("Facturas", "Facturas", "Invoices", "Faturas", "Fatture", "Factures", "Rechnungen", "发票"),
    ("Ver factura →", "Ver factura →", "View invoice →", "Ver fatura →", "Visualizza fattura →",
     "Voir la facture →", "Rechnung ansehen →", "查看发票 →"),
    ("¿Necesitás cambiar algo?", "¿Necesitás cambiar algo?", "Need to change something?", "Precisa alterar algo?",
     "Devi modificare qualcosa?", "Besoin de modifier quelque chose ?", "Möchten Sie etwas ändern?", "需要修改订单吗？"),
    ("Contale a Ventas qué querés modificar (cantidad, tamaño, sacar un producto) y te contactamos para confirmarlo.",
     "Contale a Ventas qué querés modificar (cantidad, tamaño, sacar un producto) y te contactamos para confirmarlo.",
     "Tell our Sales team what you'd like to change (quantity, size, remove a product) and we'll contact you to confirm it.",
     "Conte para Vendas o que você quer modificar (quantidade, tamanho, retirar um produto) e entraremos em contato para confirmar.",
     "Racconta al team Vendite cosa vuoi modificare (quantità, dimensione, rimuovere un prodotto) e ti contatteremo per confermarlo.",
     "Indiquez à notre équipe commerciale ce que vous souhaitez modifier (quantité, taille, retirer un produit) et nous vous contacterons pour confirmer.",
     "Teilen Sie unserem Vertrieb mit, was Sie ändern möchten (Menge, Größe, ein Produkt entfernen), und wir melden uns zur Bestätigung.",
     "请告诉我们的销售团队您想要修改的内容（数量、尺寸、删除产品），我们会与您联系确认。"),
    ("Ej: quiero cambiar la cantidad de PD90X70 a 30 unidades", "Ej: quiero cambiar la cantidad de PD90X70 a 30 unidades",
     "E.g.: I want to change the quantity of PD90X70 to 30 units", "Ex: quero alterar a quantidade de PD90X70 para 30 unidades",
     "Es: voglio cambiare la quantità di PD90X70 a 30 unità", "Ex. : je souhaite changer la quantité de PD90X70 à 30 unités",
     "Z. B.: Ich möchte die Menge von PD90X70 auf 30 Einheiten ändern", "例如：我想将PD90X70的数量改为30件"),
    ("Enviar pedido de cambio", "Enviar pedido de cambio", "Send change request", "Enviar pedido de alteração",
     "Invia richiesta di modifica", "Envoyer la demande de modification", "Änderungsanfrage senden", "提交变更请求"),
    ("Cancelar pedido", "Cancelar pedido", "Cancel order", "Cancelar pedido", "Annulla ordine",
     "Annuler la commande", "Bestellung stornieren", "取消订单"),
    ("Este pedido ya está cancelado.", "Este pedido ya está cancelado.", "This order is already cancelled.",
     "Este pedido já está cancelado.", "Questo ordine è già stato annullato.", "Cette commande est déjà annulée.",
     "Diese Bestellung wurde bereits storniert.", "该订单已被取消。"),
    ("Este pedido ya está en proceso — para cambiarlo o cancelarlo, escribinos por WhatsApp o a",
     "Este pedido ya está en proceso — para cambiarlo o cancelarlo, escribinos por WhatsApp o a",
     "This order is already being processed — to change or cancel it, write to us on WhatsApp or at",
     "Este pedido já está em processamento — para alterá-lo ou cancelá-lo, escreva para nós pelo WhatsApp ou para",
     "Questo ordine è già in lavorazione — per modificarlo o annullarlo, scrivici su WhatsApp o a",
     "Cette commande est déjà en cours de traitement — pour la modifier ou l'annuler, écrivez-nous sur WhatsApp ou à",
     "Diese Bestellung wird bereits bearbeitet — um sie zu ändern oder zu stornieren, schreiben Sie uns auf WhatsApp oder an",
     "该订单正在处理中 — 如需修改或取消，请通过WhatsApp联系我们，或发送邮件至"),
]

bulk_translate(VIEW_ID, ROWS)
