# -*- coding: utf-8 -*-
from translate_helpers import bulk_translate

VIEW_ID = 2735  # trabaja_con_nosotros_template

SPAN = '<span style="display:block; font-size:13px; font-weight:600; color:#5a4f44; margin-bottom:6px;">{}</span>'

ROWS = [
    ("Trabajá con nosotros — Cartotécnica Hores", "Trabajá con nosotros — Cartotécnica Hores",
     "Work with us — Cartotécnica Hores", "Trabalhe conosco — Cartotécnica Hores",
     "Lavora con noi — Cartotécnica Hores", "Travaillez avec nous — Cartotécnica Hores",
     "Arbeite mit uns — Cartotécnica Hores", "加入我们 — Cartotécnica Hores"),
    ("Sumate al equipo de Cartotécnica Hores. Dejanos tu currículum y te contactamos cuando surja una búsqueda que coincida con tu perfil.",
     "Sumate al equipo de Cartotécnica Hores. Dejanos tu currículum y te contactamos cuando surja una búsqueda que coincida con tu perfil.",
     "Join the Cartotécnica Hores team. Send us your résumé and we'll reach out when an opening matches your profile.",
     "Junte-se à equipe da Cartotécnica Hores. Envie seu currículo e entraremos em contato quando surgir uma vaga compatível com seu perfil.",
     "Unisciti al team di Cartotécnica Hores. Lasciaci il tuo curriculum e ti contattiamo quando si presenta una posizione in linea con il tuo profilo.",
     "Rejoignez l'équipe de Cartotécnica Hores. Laissez-nous votre CV et nous vous contacterons dès qu'un poste correspond à votre profil.",
     "Werde Teil des Cartotécnica-Hores-Teams. Hinterlassen Sie uns Ihren Lebenslauf, wir melden uns bei einer passenden Stelle.",
     "加入 Cartotécnica Hores 团队。请提交您的简历，一旦有合适的职位空缺我们将与您联系。"),
    ("Inicio", "Inicio", "Home", "Início", "Home", "Accueil", "Startseite", "首页"),
    ('<span style="opacity:.6;">/</span> Trabajá con nosotros',
     '<span style="opacity:.6;">/</span> Trabajá con nosotros',
     '<span style="opacity:.6;">/</span> Work with us',
     '<span style="opacity:.6;">/</span> Trabalhe conosco',
     '<span style="opacity:.6;">/</span> Lavora con noi',
     '<span style="opacity:.6;">/</span> Travaillez avec nous',
     '<span style="opacity:.6;">/</span> Arbeite mit uns',
     '<span style="opacity:.6;">/</span> 加入我们'),
    ("Trabajá con nosotros", "Trabajá con nosotros", "Work with us", "Trabalhe conosco", "Lavora con noi",
     "Travaillez avec nous", "Arbeite mit uns", "加入我们"),
    ("Sumate al equipo de Cartotécnica Hores", "Sumate al equipo de Cartotécnica Hores",
     "Join the Cartotécnica Hores team", "Junte-se à equipe da Cartotécnica Hores",
     "Unisciti al team di Cartotécnica Hores", "Rejoignez l'équipe de Cartotécnica Hores",
     "Werde Teil des Cartotécnica-Hores-Teams", "加入 Cartotécnica Hores 团队"),
    ("Dejanos tu currículum. Lo sumamos a nuestra base de postulantes y te contactamos cuando surja una búsqueda que coincida con tu perfil.",
     "Dejanos tu currículum. Lo sumamos a nuestra base de postulantes y te contactamos cuando surja una búsqueda que coincida con tu perfil.",
     "Send us your résumé. We'll add it to our candidate pool and reach out when an opening matches your profile.",
     "Envie seu currículo. Vamos incluí-lo em nosso banco de candidatos e entrar em contato quando surgir uma vaga compatível com seu perfil.",
     "Lasciaci il tuo curriculum. Lo aggiungiamo al nostro database di candidati e ti contattiamo quando si presenta una posizione in linea con il tuo profilo.",
     "Laissez-nous votre CV. Nous l'ajoutons à notre base de candidats et vous contactons dès qu'un poste correspond à votre profil.",
     "Hinterlassen Sie uns Ihren Lebenslauf. Wir nehmen ihn in unseren Bewerberpool auf und melden uns, sobald eine passende Stelle frei wird.",
     "请提交您的简历。我们会将其纳入候选人库，一旦有合适的职位空缺即与您联系。"),
    ("Planta de Cartotécnica Hores en Bell Ville", "Planta de Cartotécnica Hores en Bell Ville",
     "Cartotécnica Hores plant in Bell Ville", "Fábrica da Cartotécnica Hores em Bell Ville",
     "Stabilimento Cartotécnica Hores a Bell Ville", "Usine Cartotécnica Hores à Bell Ville",
     "Werk Cartotécnica Hores in Bell Ville", "位于贝尔维尔的 Cartotécnica Hores 工厂"),
    ("Revisá el formulario: completá nombre y un email válido.",
     "Revisá el formulario: completá nombre y un email válido.",
     "Check the form: fill in your name and a valid email.",
     "Confira o formulário: preencha o nome e um email válido.",
     "Controlla il modulo: inserisci nome e un'email valida.",
     "Vérifiez le formulaire : indiquez un nom et un email valide.",
     "Bitte überprüfen Sie das Formular: Name und gültige E-Mail-Adresse eingeben.",
     "请检查表单：填写姓名和有效的电子邮箱。"),
    ("Falta adjuntar tu currículum.", "Falta adjuntar tu currículum.", "You need to attach your résumé.",
     "Falta anexar seu currículo.", "Devi allegare il tuo curriculum.", "Vous devez joindre votre CV.",
     "Bitte fügen Sie Ihren Lebenslauf bei.", "请上传您的简历。"),
    ("El currículum tiene que ser un PDF o un Word (.pdf, .doc, .docx).",
     "El currículum tiene que ser un PDF o un Word (.pdf, .doc, .docx).",
     "Your résumé needs to be a PDF or Word file (.pdf, .doc, .docx).",
     "O currículo precisa ser um PDF ou Word (.pdf, .doc, .docx).",
     "Il curriculum deve essere un PDF o un Word (.pdf, .doc, .docx).",
     "Le CV doit être un fichier PDF ou Word (.pdf, .doc, .docx).",
     "Der Lebenslauf muss eine PDF- oder Word-Datei sein (.pdf, .doc, .docx).",
     "简历文件必须是PDF或Word格式（.pdf、.doc、.docx）。"),
    ("El archivo pesa demasiado — el límite es 5 MB.",
     "El archivo pesa demasiado — el límite es 5 MB.",
     "The file is too large — the limit is 5 MB.",
     "O arquivo é muito grande — o limite é 5 MB.",
     "Il file è troppo pesante — il limite è 5 MB.",
     "Le fichier est trop volumineux — la limite est de 5 Mo.",
     "Die Datei ist zu groß — das Limit liegt bei 5 MB.",
     "文件过大 — 上限为5MB。"),
    (SPAN.format("Nombre*"), SPAN.format("Nombre*"), SPAN.format("Name*"), SPAN.format("Nome*"),
     SPAN.format("Nome*"), SPAN.format("Nom*"), SPAN.format("Name*"), SPAN.format("姓名*")),
    (SPAN.format("Teléfono"), SPAN.format("Teléfono"), SPAN.format("Phone"), SPAN.format("Telefone"),
     SPAN.format("Telefono"), SPAN.format("Téléphone"), SPAN.format("Telefon"), SPAN.format("电话")),
    (SPAN.format("Email*"), SPAN.format("Email*"), SPAN.format("Email*"), SPAN.format("Email*"),
     SPAN.format("Email*"), SPAN.format("E-mail*"), SPAN.format("E-Mail*"), SPAN.format("邮箱*")),
    (SPAN.format("Área de interés"), SPAN.format("Área de interés"), SPAN.format("Area of interest"),
     SPAN.format("Área de interesse"), SPAN.format("Area di interesse"), SPAN.format("Domaine d'intérêt"),
     SPAN.format("Interessenbereich"), SPAN.format("意向岗位")),
    ("Ej: Producción, Administración, Mantenimiento...", "Ej: Producción, Administración, Mantenimiento...",
     "E.g.: Production, Administration, Maintenance...", "Ex.: Produção, Administração, Manutenção...",
     "Es.: Produzione, Amministrazione, Manutenzione...", "Ex. : Production, Administration, Maintenance...",
     "Z. B.: Produktion, Verwaltung, Wartung...", "例如：生产、行政、维护……"),
    (SPAN.format("Comentario"), SPAN.format("Comentario"), SPAN.format("Comment"), SPAN.format("Comentário"),
     SPAN.format("Commento"), SPAN.format("Commentaire"), SPAN.format("Kommentar"), SPAN.format("留言")),
    (SPAN.format("Currículum*"), SPAN.format("Currículum*"), SPAN.format("Résumé*"), SPAN.format("Currículo*"),
     SPAN.format("Curriculum*"), SPAN.format("CV*"), SPAN.format("Lebenslauf*"), SPAN.format("简历*")),
    ('<span style="display:block; font-size:12px; color:#8a7a67; margin-top:6px;">PDF o Word, hasta 5 MB.</span>',
     '<span style="display:block; font-size:12px; color:#8a7a67; margin-top:6px;">PDF o Word, hasta 5 MB.</span>',
     '<span style="display:block; font-size:12px; color:#8a7a67; margin-top:6px;">PDF or Word, up to 5 MB.</span>',
     '<span style="display:block; font-size:12px; color:#8a7a67; margin-top:6px;">PDF ou Word, até 5 MB.</span>',
     '<span style="display:block; font-size:12px; color:#8a7a67; margin-top:6px;">PDF o Word, fino a 5 MB.</span>',
     '<span style="display:block; font-size:12px; color:#8a7a67; margin-top:6px;">PDF ou Word, jusqu\'à 5 Mo.</span>',
     '<span style="display:block; font-size:12px; color:#8a7a67; margin-top:6px;">PDF oder Word, bis zu 5 MB.</span>',
     '<span style="display:block; font-size:12px; color:#8a7a67; margin-top:6px;">PDF或Word格式，最大5MB。</span>'),
    ("Enviar postulación", "Enviar postulación", "Submit application", "Enviar candidatura", "Invia candidatura",
     "Envoyer la candidature", "Bewerbung senden", "提交申请"),
]

bulk_translate(VIEW_ID, ROWS)
